<template><div class="page-surface management-page approval-center-page">
  <div class="approval-center__toolbar"><a-segmented v-model:value="view" :options="views" @change="load"/><div class="approval-center__filters"><a-input v-model:value="filters.keyword" allow-clear placeholder="单号、申请人或摘要" @press-enter="load"><template #prefix><SearchOutlined/></template></a-input><a-select v-model:value="filters.businessType" allow-clear placeholder="全部业务" :options="businessTypes"/><a-select v-model:value="filters.status" allow-clear placeholder="全部状态" :options="statusOptions"/><a-range-picker v-model:value="filters.dates"/><a-button type="primary" @click="load">查询</a-button></div></div>
  <a-table row-key="businessId" bordered class="management-table" :columns="columns" :data-source="rows" :loading="loading" :pagination="{pageSize:15}" :scroll="{x:1150,y:'calc(100vh - 340px)'}"><template #bodyCell="{column,record}"><template v-if="column.key==='type'"><span class="business-type"><component :is="typeMap[record.businessType].icon"/><b>{{typeMap[record.businessType].name}}</b></span></template><template v-else-if="column.key==='summary'"><span class="approval-summary" :title="record.summary">{{record.summary}}</span></template><template v-else-if="column.key==='status'"><a-tag :color="statusColors[record.status]||'default'">{{statusNames[record.status]||record.status}}</a-tag></template><template v-else-if="column.key==='applyTime'">{{date(record.applyTime)}}</template><template v-else-if="column.key==='approveTime'">{{date(record.approveTime)}}</template><template v-else-if="column.key==='actions'"><a-button size="small" type="primary" ghost @click="open(record)"><ArrowRightOutlined/>进入业务</a-button></template></template></a-table>
</div></template>
<script setup lang="ts">
import{CalendarOutlined,ArrowRightOutlined,ExperimentOutlined,SearchOutlined,ToolOutlined}from'@ant-design/icons-vue';import dayjs from'dayjs';import{onMounted,reactive,ref}from'vue';import{useRouter}from'vue-router';import{operationsApi}from'../../api/operations';import type{UnifiedApprovalDto}from'../../types/operations';
const router=useRouter(),view=ref('mine'),rows=ref<UnifiedApprovalDto[]>([]),loading=ref(false),filters=reactive<any>({keyword:'',businessType:undefined,status:undefined,dates:null});const views=[{label:'我的申请',value:'mine'},{label:'待我审批',value:'pending'},{label:'我已审批',value:'processed'},{label:'取消与驳回',value:'history'}],businessTypes=[{label:'仪器预约',value:'booking'},{label:'物资领用',value:'requisition'},{label:'设备报修',value:'repair'}],statusNames:any={pending:'待审核',approved:'已通过',rejected:'已驳回',cancelled:'已取消',completed:'已完成',repairing:'维修中'},statusColors:any={pending:'gold',approved:'green',rejected:'red',cancelled:'default',completed:'blue',repairing:'orange'},statusOptions=Object.entries(statusNames).map(([value,label])=>({value,label})),typeMap:any={booking:{name:'仪器预约',icon:CalendarOutlined},requisition:{name:'物资领用',icon:ExperimentOutlined},repair:{name:'设备报修',icon:ToolOutlined}};const columns:any[]=[{title:'业务类型',key:'type',width:130},{title:'业务单号',dataIndex:'businessNo',width:210},{title:'申请人',dataIndex:'applicantName',width:110},{title:'申请时间',key:'applyTime',width:170},{title:'摘要',key:'summary'},{title:'状态',key:'status',width:90},{title:'审批人',dataIndex:'approverName',width:110},{title:'审批时间',key:'approveTime',width:170},{title:'操作',key:'actions',width:120,fixed:'right'}];onMounted(load);async function load(){loading.value=true;try{rows.value=await operationsApi.approvals({view:view.value,businessType:filters.businessType,status:filters.status,keyword:filters.keyword||undefined,startTime:filters.dates?.[0]?.format('YYYY-MM-DD'),endTime:filters.dates?.[1]?.format('YYYY-MM-DD')});}finally{loading.value=false;}}function open(record:any){router.push({path:record.detailPath,query:{businessId:record.businessId}});}function date(value?:string|null){return value?dayjs(value).format('YYYY-MM-DD HH:mm'):'-';}
</script>
<style scoped>.approval-center__toolbar{display:flex;flex-direction:column;gap:14px;margin-bottom:14px}.approval-center__filters{display:grid;grid-template-columns:minmax(220px,1fr) 150px 140px 260px auto;gap:10px}.business-type{display:flex;align-items:center;gap:8px}.business-type svg{color:var(--primary-color,#1677ff)}.approval-summary{display:block;max-width:360px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:900px){.approval-center__filters{grid-template-columns:1fr 1fr}.approval-center__filters>:first-child{grid-column:1/-1}}</style>
