<template>
  <div class="page-surface management-page inventory-business-page">
    <PageToolbar eyebrow="Inventory" :title="config.title"><a-button v-if="exportType&&has('lab:export')" @click="operationsApi.export(exportType)"><DownloadOutlined />导出</a-button><a-button v-if="canCreate" type="primary" class="action-create" @click="openCreate">{{ config.action }}</a-button></PageToolbar>
    <a-table row-key="id" class="management-table" bordered :columns="columns" :data-source="rows" :loading="loading" :pagination="{pageSize:12}" :scroll="{x:1100,y:'calc(100vh - 330px)'}">
      <template #bodyCell="{column,record}">
        <template v-if="column.key==='type'">{{ record.materialType==='reagent'?'试剂':'耗材' }}</template>
        <template v-else-if="column.key==='active'"><a-tag :color="record.isActive?'green':'default'">{{record.isActive?'启用':'停用'}}</a-tag></template>
        <template v-else-if="column.key==='warning'"><a-tag :color="warningColor[record.warningStatus]">{{warningText[record.warningStatus]}}</a-tag></template>
        <template v-else-if="column.key==='status'"><a-tag :color="statusColor[record.status]">{{statusText[record.status]||record.status}}</a-tag></template>
        <template v-else-if="column.key==='quantity'"><span :class="{'stock-negative':record.quantity<0}">{{number(record.quantity)}}</span></template>
        <template v-else-if="column.key==='items'"><div class="requisition-items-cell"><span v-for="item in record.items" :key="item.id">{{item.materialName}} × {{number(item.approvedQuantity??item.requestQuantity)}}{{item.unitName}}</span></div></template>
        <template v-else-if="column.key==='actions'"><a-space wrap>
          <a-button v-if="mode==='materials'&&has('lab:material:manage')" size="small" class="action-edit" @click="openEdit(record)">编辑</a-button>
          <a-button v-if="mode==='batches'&&has('lab:stock:adjust')" size="small" class="action-edit" @click="openAdjust(record)">调整</a-button>
          <a-button v-if="mode==='requisitions'&&record.status==='pending'&&has('lab:requisition:cancel')" size="small" class="action-delete" @click="cancel(record.id)">取消</a-button>
          <template v-if="mode==='approvals'&&record.status==='pending'"><a-button size="small" class="action-edit" @click="openApproval(record)">通过</a-button><a-button size="small" class="action-delete" @click="reject(record.id)">驳回</a-button></template>
        </a-space></template>
      </template>
    </a-table>

    <a-modal v-model:open="editorOpen" :title="editing?'编辑试剂耗材':config.action" width="720px" @ok="save">
      <a-form layout="vertical">
        <template v-if="mode==='materials'">
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="物资编码"><a-input v-model:value="form.materialCode" :disabled="!!editing" /></a-form-item></a-col><a-col :span="12"><a-form-item label="物资名称"><a-input v-model:value="form.materialName" /></a-form-item></a-col></a-row>
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="物资类型"><a-select v-model:value="form.materialType" :options="materialTypes" /></a-form-item></a-col><a-col :span="12"><a-form-item label="分类"><a-select v-model:value="form.categoryId" allow-clear :options="categoryOptions" /></a-form-item></a-col></a-row>
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="规格"><a-input v-model:value="form.specification" /></a-form-item></a-col><a-col :span="12"><a-form-item label="CAS号"><a-input v-model:value="form.casNo" /></a-form-item></a-col></a-row>
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="计量单位"><a-select v-model:value="form.unitId" :options="unitOptions" /></a-form-item></a-col><a-col :span="12"><a-form-item label="供应商"><a-select v-model:value="form.supplierId" allow-clear :options="supplierOptions" /></a-form-item></a-col></a-row>
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="存放位置"><a-select v-model:value="form.storageLocationId" show-search :options="locationOptions" /></a-form-item></a-col><a-col :span="12"><a-form-item label="最低库存"><a-input-number v-model:value="form.minStock" :min="0" style="width:100%" /></a-form-item></a-col></a-row>
          <a-form-item label="说明"><a-textarea v-model:value="form.description" :rows="3" /></a-form-item><a-checkbox v-model:checked="form.isActive">启用</a-checkbox>
        </template>
        <template v-else-if="mode==='batches'">
          <a-form-item label="物资"><a-select v-model:value="form.materialId" show-search :options="materialOptions" /></a-form-item>
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="批次号"><a-input v-model:value="form.batchNo" /></a-form-item></a-col><a-col :span="12"><a-form-item label="入库数量"><a-input-number v-model:value="form.quantity" :min="0.0001" style="width:100%" /></a-form-item></a-col></a-row>
          <a-row :gutter="16"><a-col :span="12"><a-form-item label="生产日期"><a-date-picker v-model:value="form.productionDate" style="width:100%" /></a-form-item></a-col><a-col :span="12"><a-form-item label="有效期"><a-date-picker v-model:value="form.expiryDate" style="width:100%" /></a-form-item></a-col></a-row>
          <a-form-item label="单位价格"><a-input-number v-model:value="form.unitPrice" :min="0" :precision="2" style="width:100%" /></a-form-item><a-form-item label="备注"><a-input v-model:value="form.remark" /></a-form-item>
        </template>
        <template v-else-if="mode==='requisitions'">
          <a-form-item label="课题组"><a-select v-model:value="form.groupId" allow-clear :options="groupOptions" /></a-form-item><a-form-item label="领用用途"><a-textarea v-model:value="form.purpose" :rows="3" /></a-form-item>
          <div class="requisition-editor"><div v-for="(item,index) in form.items" :key="index" class="requisition-editor__row"><a-select v-model:value="item.materialId" show-search :options="materialOptions" placeholder="选择物资" /><a-input-number v-model:value="item.quantity" :min="0.0001" placeholder="数量" /><a-button danger type="text" @click="form.items.splice(index,1)"><DeleteOutlined /></a-button></div><a-button block @click="form.items.push({materialId:undefined,quantity:1})"><PlusOutlined />添加物资</a-button></div>
        </template>
      </a-form>
    </a-modal>
    <a-modal v-model:open="adjustOpen" title="调整批次库存" @ok="saveAdjust"><a-form layout="vertical"><a-form-item label="调整数量"><a-input-number v-model:value="adjustForm.quantity" style="width:100%" /></a-form-item><a-form-item label="调整原因"><a-textarea v-model:value="adjustForm.reason" :rows="3" /></a-form-item></a-form></a-modal>
    <a-modal v-model:open="approvalOpen" title="审批领用申请" width="620px" @ok="saveApproval"><a-form layout="vertical"><div v-for="item in approvalForm.items" :key="item.itemId" class="approval-item"><span>{{item.materialName}}</span><a-input-number v-model:value="item.approvedQuantity" :min="0.0001" :max="item.requestQuantity" /><small>申请 {{number(item.requestQuantity)}}</small></div><a-form-item label="审批意见"><a-textarea v-model:value="approvalForm.remark" :rows="3" /></a-form-item></a-form></a-modal>
  </div>
</template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue';import {DeleteOutlined,DownloadOutlined,PlusOutlined} from '@ant-design/icons-vue';import {message,Modal} from 'ant-design-vue';import PageToolbar from '../../components/PageToolbar.vue';import {inventoryApi} from '../../api/inventory';import {labFoundationApi} from '../../api/lab';import {useAuthStore} from '../../stores/auth';import type {MaterialDto} from '../../types/inventory';import type {LocationDto} from '../../types/lab';import {operationsApi} from '../../api/operations';
const props=defineProps<{mode:'materials'|'batches'|'flows'|'requisitions'|'approvals'|'warnings'}>();const mode=computed(()=>props.mode),auth=useAuthStore();const rows=ref<any[]>([]),materials=ref<MaterialDto[]>([]),locations=ref<LocationDto[]>([]),suppliers=ref<any[]>([]),groups=ref<any[]>([]),categories=ref<any[]>([]),units=ref<any[]>([]);const loading=ref(false),editorOpen=ref(false),editing=ref<any>(null),adjustOpen=ref(false),adjustTarget=ref<any>(null),approvalOpen=ref(false),approvalTarget=ref<any>(null);const form=reactive<any>({items:[]}),adjustForm=reactive({quantity:0,reason:''}),approvalForm=reactive<any>({items:[],remark:''});
const configs:any={materials:{title:'试剂耗材',action:'新增物资'},batches:{title:'批次库存',action:'登记入库'},flows:{title:'库存流水',action:'刷新'},requisitions:{title:'领用申请',action:'提交申请'},approvals:{title:'领用审批',action:'刷新'},warnings:{title:'库存预警',action:'刷新'}};const config=computed(()=>configs[mode.value]);const createCodes:any={materials:'lab:material:manage',batches:'lab:stock:in',requisitions:'lab:requisition:create'};const canCreate=computed(()=>['flows','approvals','warnings'].includes(mode.value)||has(createCodes[mode.value]));
const exportType=computed(()=>mode.value==='materials'?'materials':mode.value==='flows'?'stock-flows':['requisitions','approvals'].includes(mode.value)?'requisitions':'');
const maps:any={materials:[{title:'编码',dataIndex:'materialCode'},{title:'名称',dataIndex:'materialName'},{title:'类型',key:'type'},{title:'规格',dataIndex:'specification'},{title:'单位',dataIndex:'unitName'},{title:'库存',dataIndex:'currentStock'},{title:'最低库存',dataIndex:'minStock'},{title:'位置',dataIndex:'storageLocationName'},{title:'状态',key:'active',width:80},{title:'操作',key:'actions',width:90}],batches:[{title:'物资',dataIndex:'materialName'},{title:'批次号',dataIndex:'batchNo'},{title:'入库数量',dataIndex:'inQuantity'},{title:'可用库存',dataIndex:'availableQuantity'},{title:'有效期',dataIndex:'expiryDate'},{title:'预警',key:'warning',width:90},{title:'操作',key:'actions',width:90}],flows:[{title:'流水号',dataIndex:'flowNo'},{title:'物资',dataIndex:'materialName'},{title:'批次',dataIndex:'batchNo'},{title:'类型',dataIndex:'flowType'},{title:'变动量',key:'quantity'},{title:'变动前',dataIndex:'beforeQuantity'},{title:'变动后',dataIndex:'afterQuantity'},{title:'操作人',dataIndex:'operatorName'},{title:'备注',dataIndex:'remark'}],requisitions:[{title:'申请单号',dataIndex:'requisitionNo'},{title:'申请人',dataIndex:'applicantName'},{title:'课题组',dataIndex:'groupName'},{title:'明细',key:'items'},{title:'用途',dataIndex:'purpose'},{title:'状态',key:'status',width:90},{title:'操作',key:'actions',width:90}],approvals:[{title:'申请单号',dataIndex:'requisitionNo'},{title:'申请人',dataIndex:'applicantName'},{title:'明细',key:'items'},{title:'用途',dataIndex:'purpose'},{title:'状态',key:'status',width:90},{title:'操作',key:'actions',width:140}],warnings:[{title:'编码',dataIndex:'materialCode'},{title:'物资',dataIndex:'materialName'},{title:'当前库存',dataIndex:'currentStock'},{title:'最低库存',dataIndex:'minStock'},{title:'临期批次',dataIndex:'expiringBatchCount'},{title:'过期批次',dataIndex:'expiredBatchCount'},{title:'预警',key:'warning',width:90}]};const columns=computed(()=>maps[mode.value]);
const warningText:any={normal:'正常',low:'低库存',expiring:'临期',expired:'已过期'},warningColor:any={normal:'green',low:'orange',expiring:'gold',expired:'red'};const statusText:any={pending:'待审核',approved:'已通过',rejected:'已驳回',cancelled:'已取消'},statusColor:any={pending:'gold',approved:'green',rejected:'red',cancelled:'default'};const materialTypes=[{label:'试剂',value:'reagent'},{label:'耗材',value:'consumable'}];const materialOptions=computed(()=>materials.value.filter(x=>x.isActive).map(x=>({label:`${x.materialCode} · ${x.materialName}（库存 ${number(x.currentStock)}）`,value:x.id}))),categoryOptions=computed(()=>categories.value.map(x=>({label:x.itemLabel,value:x.id}))),unitOptions=computed(()=>units.value.map(x=>({label:x.itemLabel,value:x.id}))),supplierOptions=computed(()=>suppliers.value.map(x=>({label:x.supplierName,value:x.id}))),locationOptions=computed(()=>flatten(locations.value).map(x=>({label:x.locationName,value:x.id}))),groupOptions=computed(()=>groups.value.map(x=>({label:x.groupName,value:x.id})));
onMounted(init);watch(()=>props.mode,init);async function init(){loading.value=true;try{await refs();rows.value=mode.value==='materials'?materials.value:mode.value==='batches'?await inventoryApi.batches():mode.value==='flows'?await inventoryApi.flows():mode.value==='requisitions'?await inventoryApi.requisitions(true):mode.value==='approvals'?await inventoryApi.requisitions(false,'pending'):await inventoryApi.warnings();}finally{loading.value=false;}}async function refs(){const [m,l,s,g,t]=await Promise.all([inventoryApi.materials(),labFoundationApi.locations(undefined,true),labFoundationApi.suppliers(true),labFoundationApi.groups(undefined,true),labFoundationApi.dictTypes(true)]);materials.value=m;locations.value=l;suppliers.value=s;groups.value=g;const reagent=t.find(x=>x.dictCode==='reagent_category'),consumable=t.find(x=>x.dictCode==='consumable_category'),unit=t.find(x=>x.dictCode==='measurement_unit');categories.value=[...(reagent?await labFoundationApi.dictItems(reagent.id,true):[]),...(consumable?await labFoundationApi.dictItems(consumable.id,true):[])];units.value=unit?await labFoundationApi.dictItems(unit.id,true):[];}
function reset(){Object.assign(form,{materialCode:'',materialName:'',materialType:'reagent',categoryId:undefined,specification:'',casNo:'',unitId:undefined,supplierId:undefined,storageLocationId:undefined,minStock:0,description:'',isActive:true,materialId:undefined,batchNo:'',quantity:1,unitPrice:undefined,productionDate:null,expiryDate:null,remark:'',groupId:undefined,purpose:'',items:[{materialId:undefined,quantity:1}]});}function openCreate(){if(['flows','approvals','warnings'].includes(mode.value)){init();return;}editing.value=null;reset();editorOpen.value=true;}function openEdit(x:any){editing.value=x;reset();Object.assign(form,x);editorOpen.value=true;}
async function save(){if(mode.value==='materials'){editing.value?await inventoryApi.updateMaterial(editing.value.id,{...form}):await inventoryApi.createMaterial({...form});}else if(mode.value==='batches'){await inventoryApi.stockIn({...form,productionDate:form.productionDate?.format('YYYY-MM-DD'),expiryDate:form.expiryDate?.format('YYYY-MM-DD')});}else if(mode.value==='requisitions'){await inventoryApi.createRequisition({groupId:form.groupId,purpose:form.purpose,items:form.items});}message.success('保存成功');editorOpen.value=false;await init();}function openAdjust(x:any){adjustTarget.value=x;Object.assign(adjustForm,{quantity:0,reason:''});adjustOpen.value=true;}async function saveAdjust(){await inventoryApi.adjust(adjustTarget.value.id,adjustForm);message.success('库存已调整');adjustOpen.value=false;await init();}
function openApproval(x:any){approvalTarget.value=x;approvalForm.items=x.items.map((i:any)=>({itemId:i.id,materialName:i.materialName,requestQuantity:i.requestQuantity,approvedQuantity:i.requestQuantity}));approvalForm.remark='';approvalOpen.value=true;}async function saveApproval(){await inventoryApi.approve(approvalTarget.value.id,{items:approvalForm.items.map((x:any)=>({itemId:x.itemId,approvedQuantity:x.approvedQuantity})),remark:approvalForm.remark});message.success('审批通过并已扣减库存');approvalOpen.value=false;await init();}async function reject(id:string){Modal.confirm({title:'确认驳回该领用申请？',onOk:async()=>{await inventoryApi.reject(id);message.success('已驳回');await init();}});}async function cancel(id:string){await inventoryApi.cancel(id);message.success('已取消');await init();}function has(c?:string){return !!c&&auth.hasPermission(c);}function flatten(x:LocationDto[]):LocationDto[]{return x.flatMap(i=>[i,...flatten(i.children||[])]);}function number(v:number){return Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:4});}
</script>
