export interface Lab3dScene {id:string;labId:string;labName:string;sceneName:string;modelUrl?:string;backgroundColor:string;modelFileId?:string;version:number;isActive:boolean}
export interface Lab3dNode {id:string;code:string;name:string;type:string;x:number;y:number;z:number;scaleX:number;scaleY:number;scaleZ:number;businessType?:string;businessId?:string;status:string;detail?:string;floor?:number;upcomingBookingCount?:number;repairingInstrumentCount?:number;nextBookingTime?:string}
export interface Lab3dSceneDetail {scene:Lab3dScene;nodes:Lab3dNode[]}
export interface Lab3dSceneManage {scene:Lab3dScene;nodeCount:number;createTime:string;updateTime:string}
export interface Lab3dModelVersion {fileId:string;fileName:string;fileSize:number;uploaderId:string;createTime:string;isCurrent:boolean}
export interface Lab3dSceneRequest {labId:string;sceneName:string;backgroundColor:string;isActive:boolean}
export interface Lab3dNodeRequest {code:string;name:string;type:string;x:number;y:number;z:number;scaleX:number;scaleY:number;scaleZ:number;sortNo:number}
export interface Lab3dNodeStatus {nodeId:string;status:string;detail?:string}
export interface LabSpatialInstrument {id:string;code:string;name:string;status:string;model?:string;locationName:string;upcomingBookingCount:number;nextBookingTime?:string;repairStatus?:string}
export interface LabSpatialRoom {id:string;code:string;name:string;buildingName:string;floorName:string;floorNumber:number;fullPath:string;upcomingBookingCount:number;repairingInstrumentCount:number;instruments:LabSpatialInstrument[]}
export interface LabSpatialLab {id:string;code:string;name:string;description?:string;rooms:LabSpatialRoom[]}
export interface LabSpatialStatus {nodeId:string;nodeType:string;status:string;detail:string;upcomingBookingCount:number;repairingInstrumentCount:number;nextBookingTime?:string}
