-- 在 Navicat 中使用拥有 CREATE USER 权限的管理员账号（如 SYSTEM）执行。
-- Oracle 中通常以“用户/Schema”承载一个应用数据库。
CREATE USER HXS_AISYSTEM IDENTIFIED BY "system123"
  DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO HXS_AISYSTEM;
