-- 使用 HXS_AISYSTEM 用户连接后执行。
CREATE TABLE HXS_APP_USER (
    ID RAW(16) NOT NULL,
    USER_NAME VARCHAR2(100 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR),
    PASSWORD_HASH VARCHAR2(300 CHAR) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HXS_APP_USER PRIMARY KEY (ID),
    CONSTRAINT CK_HXS_APP_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);
CREATE UNIQUE INDEX UX_HXS_APP_USER_NAME ON HXS_APP_USER (USER_NAME);

COMMENT ON TABLE HXS_APP_USER IS '系统用户表';
COMMENT ON COLUMN HXS_APP_USER.ID IS '用户ID，RAW(16)，由 SYS_GUID() 生成';
COMMENT ON COLUMN HXS_APP_USER.USER_NAME IS '登录用户名，唯一';
COMMENT ON COLUMN HXS_APP_USER.DISPLAY_NAME IS '显示名称/昵称，用于页面展示';
COMMENT ON COLUMN HXS_APP_USER.PASSWORD_HASH IS '密码哈希，不保存明文密码；忘记密码时重置此字段';
COMMENT ON COLUMN HXS_APP_USER.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_APP_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_APP_USER.UPDATE_TIME IS '更新时间';

CREATE TABLE HXS_AI_CONVERSATION (
    ID RAW(16) NOT NULL, TITLE VARCHAR2(200 CHAR), CREATE_TIME TIMESTAMP(6) NOT NULL,
    UPDATE_TIME TIMESTAMP(6) NOT NULL, CONSTRAINT PK_HXS_AI_CONVERSATION PRIMARY KEY (ID)
);
COMMENT ON TABLE HXS_AI_CONVERSATION IS 'AI 会话表';
COMMENT ON COLUMN HXS_AI_CONVERSATION.ID IS '会话ID，RAW(16)，由应用或数据库生成';
COMMENT ON COLUMN HXS_AI_CONVERSATION.TITLE IS '会话标题';
COMMENT ON COLUMN HXS_AI_CONVERSATION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_AI_CONVERSATION.UPDATE_TIME IS '更新时间';

CREATE TABLE HXS_AI_MESSAGE (
    ID RAW(16) NOT NULL, CONVERSATION_ID RAW(16) NOT NULL, ROLE VARCHAR2(20 CHAR) NOT NULL,
    CONTENT CLOB NOT NULL, CREATE_TIME TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_HXS_AI_MESSAGE PRIMARY KEY (ID),
    CONSTRAINT FK_HXS_AI_MESSAGE_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES HXS_AI_CONVERSATION (ID)
);
CREATE INDEX IX_HXS_AI_MESSAGE_CONVERSATION ON HXS_AI_MESSAGE (CONVERSATION_ID, CREATE_TIME);
COMMENT ON TABLE HXS_AI_MESSAGE IS 'AI 消息表';
COMMENT ON COLUMN HXS_AI_MESSAGE.ID IS '消息ID，RAW(16)，由应用或数据库生成';
COMMENT ON COLUMN HXS_AI_MESSAGE.CONVERSATION_ID IS '所属会话ID，关联 HXS_AI_CONVERSATION.ID';
COMMENT ON COLUMN HXS_AI_MESSAGE.ROLE IS '消息角色，例如 user、assistant、system';
COMMENT ON COLUMN HXS_AI_MESSAGE.CONTENT IS '消息内容';
COMMENT ON COLUMN HXS_AI_MESSAGE.CREATE_TIME IS '创建时间';

INSERT INTO HXS_APP_USER (
    ID, USER_NAME, DISPLAY_NAME, PASSWORD_HASH, IS_ACTIVE, CREATE_TIME, UPDATE_TIME
) VALUES (
    SYS_GUID(),
    'admin',
    '系统管理员',
    'PBKDF2-SHA256$100000$Z8FQdKYJmn+9Xni6Sw5pyw==$1FdRLFcdr36OalrfjPiGN9se2EDWrdSNwOkIWN31E5c=',
    1,
    SYSTIMESTAMP,
    SYSTIMESTAMP
);

COMMIT;
