-- 使用 HXS_AISYSTEM 用户连接后执行。可重复执行。
DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_APP_USER';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_APP_USER (
                ID RAW(16) NOT NULL,
                USER_NAME VARCHAR2(100 CHAR) NOT NULL,
                DISPLAY_NAME VARCHAR2(100 CHAR),
                PASSWORD_HASH VARCHAR2(300 CHAR) NOT NULL,
                IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_APP_USER PRIMARY KEY (ID),
                CONSTRAINT CK_HXS_APP_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
            )';
    END IF;
END;
/

DECLARE
    index_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_count FROM USER_INDEXES WHERE INDEX_NAME = 'UX_HXS_APP_USER_NAME';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_APP_USER_NAME ON HXS_APP_USER (USER_NAME)';
    END IF;
END;
/

COMMENT ON TABLE HXS_APP_USER IS '系统用户表';
COMMENT ON COLUMN HXS_APP_USER.ID IS '用户ID，RAW(16)，由 SYS_GUID() 生成';
COMMENT ON COLUMN HXS_APP_USER.USER_NAME IS '登录用户名，唯一';
COMMENT ON COLUMN HXS_APP_USER.DISPLAY_NAME IS '显示名称/昵称，用于页面展示';
COMMENT ON COLUMN HXS_APP_USER.PASSWORD_HASH IS '密码哈希，不保存明文密码；忘记密码时重置此字段';
COMMENT ON COLUMN HXS_APP_USER.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_APP_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_APP_USER.UPDATE_TIME IS '更新时间';

MERGE INTO HXS_APP_USER target
USING (
    SELECT
        'admin' AS USER_NAME,
        '系统管理员' AS DISPLAY_NAME,
        'PBKDF2-SHA256$100000$Z8FQdKYJmn+9Xni6Sw5pyw==$1FdRLFcdr36OalrfjPiGN9se2EDWrdSNwOkIWN31E5c=' AS PASSWORD_HASH
    FROM DUAL
) source
ON (target.USER_NAME = source.USER_NAME)
WHEN MATCHED THEN UPDATE SET
    target.DISPLAY_NAME = source.DISPLAY_NAME,
    target.PASSWORD_HASH = source.PASSWORD_HASH,
    target.IS_ACTIVE = 1,
    target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
    ID, USER_NAME, DISPLAY_NAME, PASSWORD_HASH, IS_ACTIVE, CREATE_TIME, UPDATE_TIME
) VALUES (
    SYS_GUID(), source.USER_NAME, source.DISPLAY_NAME, source.PASSWORD_HASH, 1, SYSTIMESTAMP, SYSTIMESTAMP
);

COMMIT;
