-- 使用 HXS_AISYSTEM 用户连接后执行。
-- 如果通过 sqlplus 执行，请先确保客户端字符集为 UTF-8：
-- export NLS_LANG=AMERICAN_AMERICA.AL32UTF8

UPDATE HXS_APP_USER
SET
    DISPLAY_NAME = '系统管理员',
    UPDATE_TIME = SYSTIMESTAMP
WHERE USER_NAME = 'admin';

COMMENT ON TABLE HXS_APP_USER IS '系统用户表';
COMMENT ON COLUMN HXS_APP_USER.ID IS '用户ID，RAW(16)，由 SYS_GUID() 生成';
COMMENT ON COLUMN HXS_APP_USER.USER_NAME IS '登录用户名，唯一';
COMMENT ON COLUMN HXS_APP_USER.DISPLAY_NAME IS '显示名称/昵称，用于页面展示';
COMMENT ON COLUMN HXS_APP_USER.PASSWORD_HASH IS '密码哈希，不保存明文密码；忘记密码时重置此字段';
COMMENT ON COLUMN HXS_APP_USER.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_APP_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_APP_USER.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE HXS_AI_CONVERSATION IS 'AI 会话表';
COMMENT ON COLUMN HXS_AI_CONVERSATION.ID IS '会话ID，RAW(16)，由应用或数据库生成';
COMMENT ON COLUMN HXS_AI_CONVERSATION.TITLE IS '会话标题';
COMMENT ON COLUMN HXS_AI_CONVERSATION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_AI_CONVERSATION.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE HXS_AI_MESSAGE IS 'AI 消息表';
COMMENT ON COLUMN HXS_AI_MESSAGE.ID IS '消息ID，RAW(16)，由应用或数据库生成';
COMMENT ON COLUMN HXS_AI_MESSAGE.CONVERSATION_ID IS '所属会话ID，关联 HXS_AI_CONVERSATION.ID';
COMMENT ON COLUMN HXS_AI_MESSAGE.ROLE IS '消息角色，例如 user、assistant、system';
COMMENT ON COLUMN HXS_AI_MESSAGE.CONTENT IS '消息内容';
COMMENT ON COLUMN HXS_AI_MESSAGE.CREATE_TIME IS '创建时间';

COMMIT;
