-- 使用 HXS_AISYSTEM 用户连接后执行。可重复执行。
-- 如果通过 sqlplus 执行，请先确保客户端字符集为 UTF-8：
-- export NLS_LANG=AMERICAN_AMERICA.AL32UTF8

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_ORG';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_SYS_ORG (
                ID RAW(16) NOT NULL,
                PARENT_ID RAW(16),
                ORG_NAME VARCHAR2(100 CHAR) NOT NULL,
                ORG_CODE VARCHAR2(50 CHAR) NOT NULL,
                ORG_TYPE VARCHAR2(30 CHAR) NOT NULL,
                SORT_NO NUMBER(10) DEFAULT 0 NOT NULL,
                IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_SYS_ORG PRIMARY KEY (ID),
                CONSTRAINT CK_HXS_SYS_ORG_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
            )';
        EXECUTE IMMEDIATE 'ALTER TABLE HXS_SYS_ORG ADD CONSTRAINT FK_HXS_SYS_ORG_PARENT FOREIGN KEY (PARENT_ID) REFERENCES HXS_SYS_ORG (ID)';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_SYS_ORG_CODE ON HXS_SYS_ORG (ORG_CODE)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_ORG_PARENT ON HXS_SYS_ORG (PARENT_ID, SORT_NO)';
    END IF;
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_USER';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_SYS_USER (
                ID RAW(16) NOT NULL,
                ORG_ID RAW(16),
                USER_NAME VARCHAR2(100 CHAR) NOT NULL,
                DISPLAY_NAME VARCHAR2(100 CHAR),
                PASSWORD_HASH VARCHAR2(300 CHAR) NOT NULL,
                PHONE VARCHAR2(30 CHAR),
                EMAIL VARCHAR2(100 CHAR),
                IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
                LAST_LOGIN_TIME TIMESTAMP(6),
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_SYS_USER PRIMARY KEY (ID),
                CONSTRAINT CK_HXS_SYS_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
                CONSTRAINT FK_HXS_SYS_USER_ORG FOREIGN KEY (ORG_ID) REFERENCES HXS_SYS_ORG (ID)
            )';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_SYS_USER_NAME ON HXS_SYS_USER (USER_NAME)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_USER_ORG ON HXS_SYS_USER (ORG_ID)';
    END IF;
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_ROLE';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_SYS_ROLE (
                ID RAW(16) NOT NULL,
                ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
                ROLE_NAME VARCHAR2(100 CHAR) NOT NULL,
                DESCRIPTION VARCHAR2(300 CHAR),
                IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_SYS_ROLE PRIMARY KEY (ID),
                CONSTRAINT CK_HXS_SYS_ROLE_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
            )';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_SYS_ROLE_CODE ON HXS_SYS_ROLE (ROLE_CODE)';
    END IF;
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_MENU';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_SYS_MENU (
                ID RAW(16) NOT NULL,
                PARENT_ID RAW(16),
                MENU_CODE VARCHAR2(100 CHAR) NOT NULL,
                MENU_NAME VARCHAR2(100 CHAR) NOT NULL,
                MENU_TYPE VARCHAR2(30 CHAR) NOT NULL,
                ROUTE_PATH VARCHAR2(200 CHAR),
                COMPONENT VARCHAR2(200 CHAR),
                ICON VARCHAR2(100 CHAR),
                PERMISSION_CODE VARCHAR2(100 CHAR),
                SORT_NO NUMBER(10) DEFAULT 0 NOT NULL,
                IS_VISIBLE NUMBER(1) DEFAULT 1 NOT NULL,
                IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_SYS_MENU PRIMARY KEY (ID),
                CONSTRAINT CK_HXS_SYS_MENU_VISIBLE CHECK (IS_VISIBLE IN (0, 1)),
                CONSTRAINT CK_HXS_SYS_MENU_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
            )';
        EXECUTE IMMEDIATE 'ALTER TABLE HXS_SYS_MENU ADD CONSTRAINT FK_HXS_SYS_MENU_PARENT FOREIGN KEY (PARENT_ID) REFERENCES HXS_SYS_MENU (ID)';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_SYS_MENU_CODE ON HXS_SYS_MENU (MENU_CODE)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_MENU_PARENT ON HXS_SYS_MENU (PARENT_ID, SORT_NO)';
    END IF;
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_USER_ROLE';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_SYS_USER_ROLE (
                ID RAW(16) NOT NULL,
                USER_ID RAW(16) NOT NULL,
                ROLE_ID RAW(16) NOT NULL,
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_SYS_USER_ROLE PRIMARY KEY (ID),
                CONSTRAINT FK_HXS_SYS_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES HXS_SYS_USER (ID),
                CONSTRAINT FK_HXS_SYS_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES HXS_SYS_ROLE (ID)
            )';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_SYS_USER_ROLE ON HXS_SYS_USER_ROLE (USER_ID, ROLE_ID)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_USER_ROLE_ROLE ON HXS_SYS_USER_ROLE (ROLE_ID)';
    END IF;
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_ROLE_MENU';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE HXS_SYS_ROLE_MENU (
                ID RAW(16) NOT NULL,
                ROLE_ID RAW(16) NOT NULL,
                MENU_ID RAW(16) NOT NULL,
                CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_HXS_SYS_ROLE_MENU PRIMARY KEY (ID),
                CONSTRAINT FK_HXS_SYS_ROLE_MENU_ROLE FOREIGN KEY (ROLE_ID) REFERENCES HXS_SYS_ROLE (ID),
                CONSTRAINT FK_HXS_SYS_ROLE_MENU_MENU FOREIGN KEY (MENU_ID) REFERENCES HXS_SYS_MENU (ID)
            )';
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_HXS_SYS_ROLE_MENU ON HXS_SYS_ROLE_MENU (ROLE_ID, MENU_ID)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_ROLE_MENU_MENU ON HXS_SYS_ROLE_MENU (MENU_ID)';
    END IF;
END;
/

COMMENT ON TABLE HXS_SYS_ORG IS '系统组织架构表';
COMMENT ON COLUMN HXS_SYS_ORG.ID IS '组织ID';
COMMENT ON COLUMN HXS_SYS_ORG.PARENT_ID IS '上级组织ID，顶级为空';
COMMENT ON COLUMN HXS_SYS_ORG.ORG_NAME IS '组织名称';
COMMENT ON COLUMN HXS_SYS_ORG.ORG_CODE IS '组织编码，唯一';
COMMENT ON COLUMN HXS_SYS_ORG.ORG_TYPE IS '组织类型，例如 company、department、team';
COMMENT ON COLUMN HXS_SYS_ORG.SORT_NO IS '排序号';
COMMENT ON COLUMN HXS_SYS_ORG.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_SYS_ORG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_SYS_ORG.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE HXS_SYS_USER IS '系统用户表';
COMMENT ON COLUMN HXS_SYS_USER.ID IS '用户ID';
COMMENT ON COLUMN HXS_SYS_USER.ORG_ID IS '所属组织/部门ID';
COMMENT ON COLUMN HXS_SYS_USER.USER_NAME IS '登录用户名，唯一';
COMMENT ON COLUMN HXS_SYS_USER.DISPLAY_NAME IS '显示名称/昵称，用于页面展示';
COMMENT ON COLUMN HXS_SYS_USER.PASSWORD_HASH IS '密码哈希，不保存明文密码';
COMMENT ON COLUMN HXS_SYS_USER.PHONE IS '手机号';
COMMENT ON COLUMN HXS_SYS_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN HXS_SYS_USER.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_SYS_USER.LAST_LOGIN_TIME IS '最后登录时间';
COMMENT ON COLUMN HXS_SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_SYS_USER.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE HXS_SYS_ROLE IS '系统角色表';
COMMENT ON COLUMN HXS_SYS_ROLE.ID IS '角色ID';
COMMENT ON COLUMN HXS_SYS_ROLE.ROLE_CODE IS '角色编码，唯一';
COMMENT ON COLUMN HXS_SYS_ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN HXS_SYS_ROLE.DESCRIPTION IS '角色描述';
COMMENT ON COLUMN HXS_SYS_ROLE.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_SYS_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_SYS_ROLE.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE HXS_SYS_MENU IS '系统菜单和权限点表';
COMMENT ON COLUMN HXS_SYS_MENU.ID IS '菜单ID';
COMMENT ON COLUMN HXS_SYS_MENU.PARENT_ID IS '上级菜单ID，顶级为空';
COMMENT ON COLUMN HXS_SYS_MENU.MENU_CODE IS '菜单编码，唯一';
COMMENT ON COLUMN HXS_SYS_MENU.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN HXS_SYS_MENU.MENU_TYPE IS '菜单类型：directory、page、button';
COMMENT ON COLUMN HXS_SYS_MENU.ROUTE_PATH IS '前端路由路径';
COMMENT ON COLUMN HXS_SYS_MENU.COMPONENT IS '前端组件路径';
COMMENT ON COLUMN HXS_SYS_MENU.ICON IS '菜单图标';
COMMENT ON COLUMN HXS_SYS_MENU.PERMISSION_CODE IS '权限标识';
COMMENT ON COLUMN HXS_SYS_MENU.SORT_NO IS '排序号';
COMMENT ON COLUMN HXS_SYS_MENU.IS_VISIBLE IS '是否可见：1可见，0隐藏';
COMMENT ON COLUMN HXS_SYS_MENU.IS_ACTIVE IS '是否启用：1启用，0停用';
COMMENT ON COLUMN HXS_SYS_MENU.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN HXS_SYS_MENU.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE HXS_SYS_USER_ROLE IS '用户角色关联表';
COMMENT ON COLUMN HXS_SYS_USER_ROLE.ID IS '主键ID';
COMMENT ON COLUMN HXS_SYS_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN HXS_SYS_USER_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN HXS_SYS_USER_ROLE.CREATE_TIME IS '创建时间';

COMMENT ON TABLE HXS_SYS_ROLE_MENU IS '角色菜单关联表';
COMMENT ON COLUMN HXS_SYS_ROLE_MENU.ID IS '主键ID';
COMMENT ON COLUMN HXS_SYS_ROLE_MENU.ROLE_ID IS '角色ID';
COMMENT ON COLUMN HXS_SYS_ROLE_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN HXS_SYS_ROLE_MENU.CREATE_TIME IS '创建时间';

MERGE INTO HXS_SYS_ORG target
USING (SELECT 'root' ORG_CODE, '总部' ORG_NAME, 'company' ORG_TYPE FROM DUAL) source
ON (target.ORG_CODE = source.ORG_CODE)
WHEN MATCHED THEN UPDATE SET target.ORG_NAME = source.ORG_NAME, target.ORG_TYPE = source.ORG_TYPE, target.IS_ACTIVE = 1, target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, PARENT_ID, ORG_NAME, ORG_CODE, ORG_TYPE, SORT_NO, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), NULL, source.ORG_NAME, source.ORG_CODE, source.ORG_TYPE, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_USER target
USING (
    SELECT
        'admin' USER_NAME,
        '系统管理员' DISPLAY_NAME,
        'PBKDF2-SHA256$100000$Z8FQdKYJmn+9Xni6Sw5pyw==$1FdRLFcdr36OalrfjPiGN9se2EDWrdSNwOkIWN31E5c=' PASSWORD_HASH,
        (SELECT ID FROM HXS_SYS_ORG WHERE ORG_CODE = 'root') ORG_ID
    FROM DUAL
) source
ON (target.USER_NAME = source.USER_NAME)
WHEN MATCHED THEN UPDATE SET target.DISPLAY_NAME = source.DISPLAY_NAME, target.PASSWORD_HASH = source.PASSWORD_HASH, target.ORG_ID = source.ORG_ID, target.IS_ACTIVE = 1, target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, ORG_ID, USER_NAME, DISPLAY_NAME, PASSWORD_HASH, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), source.ORG_ID, source.USER_NAME, source.DISPLAY_NAME, source.PASSWORD_HASH, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_ROLE target
USING (SELECT 'admin' ROLE_CODE, '系统管理员' ROLE_NAME, '拥有系统全部权限' DESCRIPTION FROM DUAL) source
ON (target.ROLE_CODE = source.ROLE_CODE)
WHEN MATCHED THEN UPDATE SET target.ROLE_NAME = source.ROLE_NAME, target.DESCRIPTION = source.DESCRIPTION, target.IS_ACTIVE = 1, target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), source.ROLE_CODE, source.ROLE_NAME, source.DESCRIPTION, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_MENU target
USING (SELECT 'dashboard' MENU_CODE, '首页总览' MENU_NAME, 'page' MENU_TYPE, '/' ROUTE_PATH, 'dashboard/index' COMPONENT, 'dashboard' ICON, 'dashboard:view' PERMISSION_CODE, 1 SORT_NO FROM DUAL) source
ON (target.MENU_CODE = source.MENU_CODE)
WHEN MATCHED THEN UPDATE SET target.PARENT_ID = NULL, target.MENU_NAME = source.MENU_NAME, target.MENU_TYPE = source.MENU_TYPE, target.ROUTE_PATH = source.ROUTE_PATH, target.COMPONENT = source.COMPONENT, target.ICON = source.ICON, target.PERMISSION_CODE = source.PERMISSION_CODE, target.SORT_NO = source.SORT_NO, target.IS_VISIBLE = 1, target.IS_ACTIVE = 1, target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, ROUTE_PATH, COMPONENT, ICON, PERMISSION_CODE, SORT_NO, IS_VISIBLE, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), NULL, source.MENU_CODE, source.MENU_NAME, source.MENU_TYPE, source.ROUTE_PATH, source.COMPONENT, source.ICON, source.PERMISSION_CODE, source.SORT_NO, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_MENU target
USING (SELECT 'sys' MENU_CODE, '系统管理' MENU_NAME, 'directory' MENU_TYPE, '/system' ROUTE_PATH, NULL COMPONENT, 'settings' ICON, NULL PERMISSION_CODE, 10 SORT_NO FROM DUAL) source
ON (target.MENU_CODE = source.MENU_CODE)
WHEN MATCHED THEN UPDATE SET target.MENU_NAME = source.MENU_NAME, target.MENU_TYPE = source.MENU_TYPE, target.ROUTE_PATH = source.ROUTE_PATH, target.COMPONENT = source.COMPONENT, target.ICON = source.ICON, target.PERMISSION_CODE = source.PERMISSION_CODE, target.SORT_NO = source.SORT_NO, target.IS_VISIBLE = 1, target.IS_ACTIVE = 1, target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, ROUTE_PATH, COMPONENT, ICON, PERMISSION_CODE, SORT_NO, IS_VISIBLE, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), NULL, source.MENU_CODE, source.MENU_NAME, source.MENU_TYPE, source.ROUTE_PATH, source.COMPONENT, source.ICON, source.PERMISSION_CODE, source.SORT_NO, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_MENU target
USING (
    SELECT 'sys:user' MENU_CODE, '用户管理' MENU_NAME, 'page' MENU_TYPE, '/system/users' ROUTE_PATH, 'system/user/index' COMPONENT, 'users' ICON, 'sys:user:list' PERMISSION_CODE, 10 SORT_NO FROM DUAL UNION ALL
    SELECT 'sys:role', '角色管理', 'page', '/system/roles', 'system/role/index', 'shield', 'sys:role:list', 20 FROM DUAL UNION ALL
    SELECT 'sys:menu', '菜单管理', 'page', '/system/menus', 'system/menu/index', 'menu', 'sys:menu:list', 30 FROM DUAL UNION ALL
    SELECT 'sys:org', '组织架构', 'page', '/system/orgs', 'system/org/index', 'building', 'sys:org:list', 40 FROM DUAL
) source
ON (target.MENU_CODE = source.MENU_CODE)
WHEN MATCHED THEN UPDATE SET target.PARENT_ID = (SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE = 'sys'), target.MENU_NAME = source.MENU_NAME, target.MENU_TYPE = source.MENU_TYPE, target.ROUTE_PATH = source.ROUTE_PATH, target.COMPONENT = source.COMPONENT, target.ICON = source.ICON, target.PERMISSION_CODE = source.PERMISSION_CODE, target.SORT_NO = source.SORT_NO, target.IS_VISIBLE = 1, target.IS_ACTIVE = 1, target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, ROUTE_PATH, COMPONENT, ICON, PERMISSION_CODE, SORT_NO, IS_VISIBLE, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), (SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE = 'sys'), source.MENU_CODE, source.MENU_NAME, source.MENU_TYPE, source.ROUTE_PATH, source.COMPONENT, source.ICON, source.PERMISSION_CODE, source.SORT_NO, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_USER_ROLE target
USING (
    SELECT u.ID USER_ID, r.ID ROLE_ID FROM HXS_SYS_USER u CROSS JOIN HXS_SYS_ROLE r
    WHERE u.USER_NAME = 'admin' AND r.ROLE_CODE = 'admin'
) source
ON (target.USER_ID = source.USER_ID AND target.ROLE_ID = source.ROLE_ID)
WHEN NOT MATCHED THEN INSERT (ID, USER_ID, ROLE_ID, CREATE_TIME)
VALUES (SYS_GUID(), source.USER_ID, source.ROLE_ID, SYSTIMESTAMP);

MERGE INTO HXS_SYS_ROLE_MENU target
USING (
    SELECT r.ID ROLE_ID, m.ID MENU_ID FROM HXS_SYS_ROLE r CROSS JOIN HXS_SYS_MENU m
    WHERE r.ROLE_CODE = 'admin' AND m.MENU_CODE IN ('dashboard', 'sys', 'sys:user', 'sys:role', 'sys:menu', 'sys:org')
) source
ON (target.ROLE_ID = source.ROLE_ID AND target.MENU_ID = source.MENU_ID)
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, CREATE_TIME)
VALUES (SYS_GUID(), source.ROLE_ID, source.MENU_ID, SYSTIMESTAMP);

COMMIT;
