-- 使用 HXS_AISYSTEM 用户连接后执行。可重复执行。

DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'HXS_AI_CONVERSATION' AND COLUMN_NAME = 'USER_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HXS_AI_CONVERSATION ADD USER_ID RAW(16)';
        EXECUTE IMMEDIATE 'ALTER TABLE HXS_AI_CONVERSATION ADD CONSTRAINT FK_HXS_AI_CONV_USER FOREIGN KEY (USER_ID) REFERENCES HXS_SYS_USER (ID)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_AI_CONV_USER ON HXS_AI_CONVERSATION (USER_ID, UPDATE_TIME)';
    END IF;
END;
/

DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'HXS_AI_MESSAGE' AND COLUMN_NAME = 'MESSAGE_TYPE';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE q'[ALTER TABLE HXS_AI_MESSAGE ADD MESSAGE_TYPE VARCHAR2(30 CHAR) DEFAULT 'text' NOT NULL]';
    END IF;

    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'HXS_AI_MESSAGE' AND COLUMN_NAME = 'METADATA';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HXS_AI_MESSAGE ADD METADATA CLOB';
    END IF;
END;
/

COMMENT ON COLUMN HXS_AI_CONVERSATION.USER_ID IS '会话所属系统用户ID';
COMMENT ON COLUMN HXS_AI_MESSAGE.MESSAGE_TYPE IS '消息类型：text、reasoning';
COMMENT ON COLUMN HXS_AI_MESSAGE.METADATA IS '结构化推理结果及模型元数据JSON';

MERGE INTO HXS_SYS_MENU target
USING (
    SELECT 'ai:reasoning' MENU_CODE, '数据推理' MENU_NAME, 'page' MENU_TYPE,
           '/ai/reasoning' ROUTE_PATH, 'ai/reasoning/index' COMPONENT,
           'bulb' ICON, 'ai:reasoning:use' PERMISSION_CODE, 5 SORT_NO
    FROM DUAL
) source
ON (target.MENU_CODE = source.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
    target.PARENT_ID = NULL,
    target.MENU_NAME = source.MENU_NAME,
    target.MENU_TYPE = source.MENU_TYPE,
    target.ROUTE_PATH = source.ROUTE_PATH,
    target.COMPONENT = source.COMPONENT,
    target.ICON = source.ICON,
    target.PERMISSION_CODE = source.PERMISSION_CODE,
    target.SORT_NO = source.SORT_NO,
    target.IS_VISIBLE = 1,
    target.IS_ACTIVE = 1,
    target.UPDATE_TIME = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
    ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, ROUTE_PATH, COMPONENT, ICON,
    PERMISSION_CODE, SORT_NO, IS_VISIBLE, IS_ACTIVE, CREATE_TIME, UPDATE_TIME
)
VALUES (
    SYS_GUID(), NULL, source.MENU_CODE, source.MENU_NAME, source.MENU_TYPE,
    source.ROUTE_PATH, source.COMPONENT, source.ICON, source.PERMISSION_CODE,
    source.SORT_NO, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP
);

MERGE INTO HXS_SYS_ROLE_MENU target
USING (
    SELECT r.ID ROLE_ID, m.ID MENU_ID
    FROM HXS_SYS_ROLE r CROSS JOIN HXS_SYS_MENU m
    WHERE r.ROLE_CODE = 'admin' AND m.MENU_CODE = 'ai:reasoning'
) source
ON (target.ROLE_ID = source.ROLE_ID AND target.MENU_ID = source.MENU_ID)
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, CREATE_TIME)
VALUES (SYS_GUID(), source.ROLE_ID, source.MENU_ID, SYSTIMESTAMP);

COMMIT;
