-- 阶段1：认证加固、审计日志与文件元数据。使用 HXS_AISYSTEM 用户执行，可重复执行。

DECLARE column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HXS_SYS_USER' AND COLUMN_NAME = 'FAILED_LOGIN_COUNT';
    IF column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE HXS_SYS_USER ADD FAILED_LOGIN_COUNT NUMBER(10) DEFAULT 0 NOT NULL'; END IF;
    SELECT COUNT(*) INTO column_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HXS_SYS_USER' AND COLUMN_NAME = 'LOCKED_UNTIL';
    IF column_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE HXS_SYS_USER ADD LOCKED_UNTIL TIMESTAMP(6)'; END IF;
END;
/

DECLARE table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_AUDIT_LOG';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE HXS_SYS_AUDIT_LOG (
            ID RAW(16) NOT NULL, USER_ID RAW(16), USER_NAME VARCHAR2(100 CHAR), MODULE_CODE VARCHAR2(100 CHAR) NOT NULL,
            ACTION_CODE VARCHAR2(100 CHAR) NOT NULL, BUSINESS_ID VARCHAR2(100 CHAR), REQUEST_PATH VARCHAR2(300 CHAR) NOT NULL,
            HTTP_METHOD VARCHAR2(20 CHAR) NOT NULL, BEFORE_DATA CLOB, AFTER_DATA CLOB, RESULT VARCHAR2(30 CHAR) NOT NULL,
            IP_ADDRESS VARCHAR2(100 CHAR), CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_HXS_SYS_AUDIT_LOG PRIMARY KEY (ID))';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_AUDIT_TIME ON HXS_SYS_AUDIT_LOG (CREATE_TIME)';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_AUDIT_USER ON HXS_SYS_AUDIT_LOG (USER_ID, CREATE_TIME)';
    END IF;
END;
/

DECLARE table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'HXS_SYS_FILE';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE HXS_SYS_FILE (
            ID RAW(16) NOT NULL, BUSINESS_TYPE VARCHAR2(50 CHAR) NOT NULL, BUSINESS_ID VARCHAR2(100 CHAR),
            ORIGINAL_NAME VARCHAR2(255 CHAR) NOT NULL, STORAGE_NAME VARCHAR2(255 CHAR) NOT NULL,
            FILE_PATH VARCHAR2(500 CHAR) NOT NULL, CONTENT_TYPE VARCHAR2(150 CHAR) NOT NULL, FILE_SIZE NUMBER(19) NOT NULL,
            UPLOADER_ID RAW(16) NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_HXS_SYS_FILE PRIMARY KEY (ID),
            CONSTRAINT FK_HXS_SYS_FILE_USER FOREIGN KEY (UPLOADER_ID) REFERENCES HXS_SYS_USER (ID))';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_HXS_SYS_FILE_BUSINESS ON HXS_SYS_FILE (BUSINESS_TYPE, BUSINESS_ID)';
    END IF;
END;
/

MERGE INTO HXS_SYS_ROLE target USING (SELECT 'lab_admin' ROLE_CODE, '实验管理员' ROLE_NAME, '管理所属实验室业务并执行审批' DESCRIPTION FROM DUAL) source
ON (target.ROLE_CODE = source.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), source.ROLE_CODE, source.ROLE_NAME, source.DESCRIPTION, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO HXS_SYS_ROLE target USING (SELECT 'lab_user' ROLE_CODE, '普通实验员' ROLE_NAME, '提交申请并维护本人实验记录' DESCRIPTION FROM DUAL) source
ON (target.ROLE_CODE = source.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, IS_ACTIVE, CREATE_TIME, UPDATE_TIME)
VALUES (SYS_GUID(), source.ROLE_CODE, source.ROLE_NAME, source.DESCRIPTION, 1, SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
