-- 阶段2：实验室基础数据。使用 HXS_AISYSTEM 用户执行，可重复执行。
DECLARE
    table_count NUMBER;
    PROCEDURE ensure_table(table_name VARCHAR2, ddl CLOB) IS
    BEGIN
        SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = table_name;
        IF table_count = 0 THEN EXECUTE IMMEDIATE ddl; END IF;
    END;
BEGIN
    ensure_table('HXS_LAB', q'[CREATE TABLE HXS_LAB (
        ID RAW(16) NOT NULL, LAB_CODE VARCHAR2(50 CHAR) NOT NULL, LAB_NAME VARCHAR2(100 CHAR) NOT NULL,
        MANAGER_ID RAW(16), DESCRIPTION VARCHAR2(500 CHAR), IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_LAB PRIMARY KEY (ID), CONSTRAINT UK_HXS_LAB_CODE UNIQUE (LAB_CODE))]');
    ensure_table('HXS_LAB_LOCATION', q'[CREATE TABLE HXS_LAB_LOCATION (
        ID RAW(16) NOT NULL, LAB_ID RAW(16) NOT NULL, PARENT_ID RAW(16), LOCATION_CODE VARCHAR2(50 CHAR) NOT NULL,
        LOCATION_NAME VARCHAR2(100 CHAR) NOT NULL, LOCATION_TYPE VARCHAR2(30 CHAR) NOT NULL, SORT_NO NUMBER(10) DEFAULT 0 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_LOCATION PRIMARY KEY (ID),
        CONSTRAINT UK_HXS_LAB_LOCATION_CODE UNIQUE (LOCATION_CODE))]');
    ensure_table('HXS_LAB_GROUP', q'[CREATE TABLE HXS_LAB_GROUP (
        ID RAW(16) NOT NULL, LAB_ID RAW(16) NOT NULL, GROUP_CODE VARCHAR2(50 CHAR) NOT NULL, GROUP_NAME VARCHAR2(100 CHAR) NOT NULL,
        LEADER_ID RAW(16), DESCRIPTION VARCHAR2(500 CHAR), IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_LAB_GROUP PRIMARY KEY (ID), CONSTRAINT UK_HXS_LAB_GROUP_CODE UNIQUE (GROUP_CODE))]');
    ensure_table('HXS_LAB_GROUP_MEMBER', q'[CREATE TABLE HXS_LAB_GROUP_MEMBER (
        ID RAW(16) NOT NULL, GROUP_ID RAW(16) NOT NULL, USER_ID RAW(16) NOT NULL, MEMBER_ROLE VARCHAR2(30 CHAR) NOT NULL,
        CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_GROUP_MEMBER PRIMARY KEY (ID),
        CONSTRAINT UK_HXS_LAB_GROUP_MEMBER UNIQUE (GROUP_ID, USER_ID))]');
    ensure_table('HXS_LAB_SUPPLIER', q'[CREATE TABLE HXS_LAB_SUPPLIER (
        ID RAW(16) NOT NULL, SUPPLIER_CODE VARCHAR2(50 CHAR) NOT NULL, SUPPLIER_NAME VARCHAR2(150 CHAR) NOT NULL,
        CONTACT_NAME VARCHAR2(100 CHAR), PHONE VARCHAR2(50 CHAR), EMAIL VARCHAR2(150 CHAR), ADDRESS VARCHAR2(300 CHAR),
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_SUPPLIER PRIMARY KEY (ID),
        CONSTRAINT UK_HXS_LAB_SUPPLIER_CODE UNIQUE (SUPPLIER_CODE))]');
    ensure_table('HXS_SYS_DICT_TYPE', q'[CREATE TABLE HXS_SYS_DICT_TYPE (
        ID RAW(16) NOT NULL, DICT_CODE VARCHAR2(50 CHAR) NOT NULL, DICT_NAME VARCHAR2(100 CHAR) NOT NULL,
        DESCRIPTION VARCHAR2(500 CHAR), IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_SYS_DICT_TYPE PRIMARY KEY (ID), CONSTRAINT UK_HXS_SYS_DICT_TYPE_CODE UNIQUE (DICT_CODE))]');
    ensure_table('HXS_SYS_DICT_ITEM', q'[CREATE TABLE HXS_SYS_DICT_ITEM (
        ID RAW(16) NOT NULL, DICT_TYPE_ID RAW(16) NOT NULL, ITEM_VALUE VARCHAR2(100 CHAR) NOT NULL,
        ITEM_LABEL VARCHAR2(100 CHAR) NOT NULL, SORT_NO NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_SYS_DICT_ITEM PRIMARY KEY (ID), CONSTRAINT UK_HXS_SYS_DICT_ITEM UNIQUE (DICT_TYPE_ID, ITEM_VALUE))]');
END;
/
COMMIT;
