-- 阶段4：试剂耗材库存闭环。应用启动时会幂等创建同结构表、菜单、权限及演示数据。
DECLARE
    table_count NUMBER;
    PROCEDURE ensure_table(name VARCHAR2, ddl CLOB) IS
    BEGIN
        SELECT COUNT(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME=name;
        IF table_count=0 THEN EXECUTE IMMEDIATE ddl; END IF;
    END;
BEGIN
    ensure_table('HXS_LAB_MATERIAL', q'[CREATE TABLE HXS_LAB_MATERIAL (ID RAW(16) NOT NULL, MATERIAL_CODE VARCHAR2(50 CHAR) NOT NULL, MATERIAL_NAME VARCHAR2(150 CHAR) NOT NULL, MATERIAL_TYPE VARCHAR2(20 CHAR) NOT NULL, CATEGORY_ID RAW(16), SPECIFICATION VARCHAR2(100 CHAR), CAS_NO VARCHAR2(80 CHAR), UNIT_ID RAW(16) NOT NULL, SUPPLIER_ID RAW(16), STORAGE_LOCATION_ID RAW(16) NOT NULL, MIN_STOCK NUMBER(18,4) DEFAULT 0 NOT NULL, DESCRIPTION VARCHAR2(500 CHAR), IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_MATERIAL PRIMARY KEY(ID), CONSTRAINT UK_HXS_LAB_MATERIAL_CODE UNIQUE(MATERIAL_CODE), CONSTRAINT CK_HXS_LAB_MATERIAL_TYPE CHECK(MATERIAL_TYPE IN ('reagent','consumable')), CONSTRAINT FK_MATERIAL_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES HXS_SYS_DICT_ITEM(ID), CONSTRAINT FK_MATERIAL_UNIT FOREIGN KEY(UNIT_ID) REFERENCES HXS_SYS_DICT_ITEM(ID), CONSTRAINT FK_MATERIAL_SUPPLIER FOREIGN KEY(SUPPLIER_ID) REFERENCES HXS_LAB_SUPPLIER(ID), CONSTRAINT FK_MATERIAL_LOCATION FOREIGN KEY(STORAGE_LOCATION_ID) REFERENCES HXS_LAB_LOCATION(ID))]');
    ensure_table('HXS_LAB_STOCK_BATCH', q'[CREATE TABLE HXS_LAB_STOCK_BATCH (ID RAW(16) NOT NULL, MATERIAL_ID RAW(16) NOT NULL, BATCH_NO VARCHAR2(80 CHAR) NOT NULL, PRODUCTION_DATE DATE, EXPIRY_DATE DATE, IN_QUANTITY NUMBER(18,4) NOT NULL, AVAILABLE_QUANTITY NUMBER(18,4) NOT NULL, UNIT_PRICE NUMBER(18,4), STOCK_IN_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_STOCK_BATCH PRIMARY KEY(ID), CONSTRAINT UK_HXS_STOCK_BATCH UNIQUE(MATERIAL_ID,BATCH_NO), CONSTRAINT CK_HXS_STOCK_BATCH_QTY CHECK(IN_QUANTITY>0 AND AVAILABLE_QUANTITY>=0), CONSTRAINT FK_STOCK_BATCH_MATERIAL FOREIGN KEY(MATERIAL_ID) REFERENCES HXS_LAB_MATERIAL(ID))]');
    ensure_table('HXS_LAB_STOCK_FLOW', q'[CREATE TABLE HXS_LAB_STOCK_FLOW (ID RAW(16) NOT NULL, FLOW_NO VARCHAR2(40 CHAR) NOT NULL, MATERIAL_ID RAW(16) NOT NULL, BATCH_ID RAW(16) NOT NULL, FLOW_TYPE VARCHAR2(20 CHAR) NOT NULL, QUANTITY NUMBER(18,4) NOT NULL, BEFORE_QUANTITY NUMBER(18,4) NOT NULL, AFTER_QUANTITY NUMBER(18,4) NOT NULL, SOURCE_TYPE VARCHAR2(30 CHAR) NOT NULL, SOURCE_ID RAW(16), OPERATOR_ID RAW(16) NOT NULL, REMARK VARCHAR2(500 CHAR), CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_STOCK_FLOW PRIMARY KEY(ID), CONSTRAINT UK_HXS_STOCK_FLOW_NO UNIQUE(FLOW_NO), CONSTRAINT FK_STOCK_FLOW_MATERIAL FOREIGN KEY(MATERIAL_ID) REFERENCES HXS_LAB_MATERIAL(ID), CONSTRAINT FK_STOCK_FLOW_BATCH FOREIGN KEY(BATCH_ID) REFERENCES HXS_LAB_STOCK_BATCH(ID), CONSTRAINT FK_STOCK_FLOW_USER FOREIGN KEY(OPERATOR_ID) REFERENCES HXS_SYS_USER(ID))]');
    ensure_table('HXS_LAB_REQUISITION', q'[CREATE TABLE HXS_LAB_REQUISITION (ID RAW(16) NOT NULL, REQUISITION_NO VARCHAR2(40 CHAR) NOT NULL, APPLICANT_ID RAW(16) NOT NULL, GROUP_ID RAW(16), PURPOSE VARCHAR2(500 CHAR) NOT NULL, STATUS VARCHAR2(20 CHAR) NOT NULL, APPROVER_ID RAW(16), APPROVE_TIME TIMESTAMP(6), APPROVE_REMARK VARCHAR2(500 CHAR), CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT PK_HXS_LAB_REQUISITION PRIMARY KEY(ID), CONSTRAINT UK_HXS_REQUISITION_NO UNIQUE(REQUISITION_NO), CONSTRAINT FK_REQ_APPLICANT FOREIGN KEY(APPLICANT_ID) REFERENCES HXS_SYS_USER(ID), CONSTRAINT FK_REQ_GROUP FOREIGN KEY(GROUP_ID) REFERENCES HXS_LAB_GROUP(ID), CONSTRAINT FK_REQ_APPROVER FOREIGN KEY(APPROVER_ID) REFERENCES HXS_SYS_USER(ID))]');
    ensure_table('HXS_LAB_REQUISITION_ITEM', q'[CREATE TABLE HXS_LAB_REQUISITION_ITEM (ID RAW(16) NOT NULL, REQUISITION_ID RAW(16) NOT NULL, MATERIAL_ID RAW(16) NOT NULL, REQUEST_QUANTITY NUMBER(18,4) NOT NULL, APPROVED_QUANTITY NUMBER(18,4), CONSTRAINT PK_HXS_LAB_REQ_ITEM PRIMARY KEY(ID), CONSTRAINT UK_HXS_LAB_REQ_ITEM UNIQUE(REQUISITION_ID,MATERIAL_ID), CONSTRAINT FK_REQ_ITEM_REQ FOREIGN KEY(REQUISITION_ID) REFERENCES HXS_LAB_REQUISITION(ID), CONSTRAINT FK_REQ_ITEM_MATERIAL FOREIGN KEY(MATERIAL_ID) REFERENCES HXS_LAB_MATERIAL(ID))]');
END;
/

-- 实验室菜单分组。
MERGE INTO HXS_SYS_MENU target
USING (
    SELECT 'lab:foundation-group' MENU_CODE, '基础资料' MENU_NAME, 'apps' ICON, 10 SORT_NO FROM DUAL UNION ALL
    SELECT 'lab:instrument-group', '仪器业务', 'experiment', 20 FROM DUAL UNION ALL
    SELECT 'lab:inventory-group', '库存业务', 'database', 30 FROM DUAL UNION ALL
    SELECT 'lab:approval-group', '审批中心', 'check', 40 FROM DUAL
) source
ON (target.MENU_CODE=source.MENU_CODE)
WHEN MATCHED THEN UPDATE SET target.PARENT_ID=(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE='lab'), target.MENU_NAME=source.MENU_NAME, target.MENU_TYPE='directory', target.ROUTE_PATH=NULL, target.COMPONENT=NULL, target.ICON=source.ICON, target.PERMISSION_CODE=NULL, target.SORT_NO=source.SORT_NO, target.IS_VISIBLE=1, target.IS_ACTIVE=1, target.UPDATE_TIME=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID,PARENT_ID,MENU_CODE,MENU_NAME,MENU_TYPE,ICON,SORT_NO,IS_VISIBLE,IS_ACTIVE,CREATE_TIME,UPDATE_TIME)
VALUES (SYS_GUID(),(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE='lab'),source.MENU_CODE,source.MENU_NAME,'directory',source.ICON,source.SORT_NO,1,1,SYSTIMESTAMP,SYSTIMESTAMP);

-- 将已有实验室页面归入对应分组。
UPDATE HXS_SYS_MENU SET PARENT_ID=(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE='lab:foundation-group'), UPDATE_TIME=SYSTIMESTAMP
WHERE MENU_CODE IN ('lab:labs','lab:locations','lab:groups','lab:suppliers','lab:dictionaries');
UPDATE HXS_SYS_MENU SET PARENT_ID=(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE='lab:instrument-group'), UPDATE_TIME=SYSTIMESTAMP
WHERE MENU_CODE IN ('lab:instruments','lab:bookings','lab:usages','lab:repairs');
UPDATE HXS_SYS_MENU SET PARENT_ID=(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE='lab:approval-group'), UPDATE_TIME=SYSTIMESTAMP
WHERE MENU_CODE='lab:booking-approvals';

-- 阶段4页面菜单。
MERGE INTO HXS_SYS_MENU target
USING (
    SELECT 'lab:materials' MENU_CODE, '试剂耗材' MENU_NAME, '/lab/materials' ROUTE_PATH, 'views/lab/MaterialView.vue' COMPONENT, 'shop' ICON, 'lab:inventory:view' PERMISSION_CODE, 10 SORT_NO, 'lab:inventory-group' PARENT_CODE FROM DUAL UNION ALL
    SELECT 'lab:stock-batches', '批次库存', '/lab/stock-batches', 'views/lab/StockBatchView.vue', 'database', 'lab:inventory:view', 20, 'lab:inventory-group' FROM DUAL UNION ALL
    SELECT 'lab:stock-flows', '库存流水', '/lab/stock-flows', 'views/lab/StockFlowView.vue', 'history', 'lab:inventory:view', 30, 'lab:inventory-group' FROM DUAL UNION ALL
    SELECT 'lab:requisitions', '领用申请', '/lab/requisitions', 'views/lab/RequisitionView.vue', 'file', 'lab:requisition:view', 40, 'lab:inventory-group' FROM DUAL UNION ALL
    SELECT 'lab:requisition-approvals', '领用审批', '/lab/requisition-approvals', 'views/lab/RequisitionApprovalView.vue', 'check', 'lab:requisition:approve', 20, 'lab:approval-group' FROM DUAL UNION ALL
    SELECT 'lab:inventory-warnings', '库存预警', '/lab/inventory-warnings', 'views/lab/InventoryWarningView.vue', 'chart', 'lab:inventory:view', 50, 'lab:inventory-group' FROM DUAL
) source
ON (target.MENU_CODE=source.MENU_CODE)
WHEN MATCHED THEN UPDATE SET target.PARENT_ID=(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE=source.PARENT_CODE), target.MENU_NAME=source.MENU_NAME, target.MENU_TYPE='page', target.ROUTE_PATH=source.ROUTE_PATH, target.COMPONENT=source.COMPONENT, target.ICON=source.ICON, target.PERMISSION_CODE=source.PERMISSION_CODE, target.SORT_NO=source.SORT_NO, target.IS_VISIBLE=1, target.IS_ACTIVE=1, target.UPDATE_TIME=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID,PARENT_ID,MENU_CODE,MENU_NAME,MENU_TYPE,ROUTE_PATH,COMPONENT,ICON,PERMISSION_CODE,SORT_NO,IS_VISIBLE,IS_ACTIVE,CREATE_TIME,UPDATE_TIME)
VALUES (SYS_GUID(),(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE=source.PARENT_CODE),source.MENU_CODE,source.MENU_NAME,'page',source.ROUTE_PATH,source.COMPONENT,source.ICON,source.PERMISSION_CODE,source.SORT_NO,1,1,SYSTIMESTAMP,SYSTIMESTAMP);

-- 阶段4操作权限，必须挂在对应页面下面。
MERGE INTO HXS_SYS_MENU target
USING (
    SELECT 'permission:lab:material:manage' MENU_CODE, '维护试剂耗材' MENU_NAME, 'lab:material:manage' PERMISSION_CODE, 'lab:materials' PARENT_CODE FROM DUAL UNION ALL
    SELECT 'permission:lab:stock:in', '登记入库', 'lab:stock:in', 'lab:stock-batches' FROM DUAL UNION ALL
    SELECT 'permission:lab:stock:adjust', '调整库存', 'lab:stock:adjust', 'lab:stock-batches' FROM DUAL UNION ALL
    SELECT 'permission:lab:requisition:create', '提交领用', 'lab:requisition:create', 'lab:requisitions' FROM DUAL UNION ALL
    SELECT 'permission:lab:requisition:cancel', '取消领用', 'lab:requisition:cancel', 'lab:requisitions' FROM DUAL UNION ALL
    SELECT 'permission:lab:requisition:approve', '审批领用', 'lab:requisition:approve', 'lab:requisition-approvals' FROM DUAL
) source
ON (target.PERMISSION_CODE=source.PERMISSION_CODE AND target.MENU_TYPE='button')
WHEN MATCHED THEN UPDATE SET target.PARENT_ID=(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE=source.PARENT_CODE), target.MENU_NAME=source.MENU_NAME, target.MENU_CODE=source.MENU_CODE, target.IS_VISIBLE=0, target.IS_ACTIVE=1, target.UPDATE_TIME=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID,PARENT_ID,MENU_CODE,MENU_NAME,MENU_TYPE,PERMISSION_CODE,SORT_NO,IS_VISIBLE,IS_ACTIVE,CREATE_TIME,UPDATE_TIME)
VALUES (SYS_GUID(),(SELECT ID FROM HXS_SYS_MENU WHERE MENU_CODE=source.PARENT_CODE),source.MENU_CODE,source.MENU_NAME,'button',source.PERMISSION_CODE,1000,0,1,SYSTIMESTAMP,SYSTIMESTAMP);

-- 超级管理员和实验管理员拥有阶段4全部页面与操作权限。
MERGE INTO HXS_SYS_ROLE_MENU target
USING (
    SELECT role.ID ROLE_ID, menu.ID MENU_ID
    FROM HXS_SYS_ROLE role CROSS JOIN HXS_SYS_MENU menu
    WHERE role.ROLE_CODE IN ('admin','lab_admin')
      AND (menu.MENU_CODE='lab' OR menu.MENU_CODE IN ('lab:foundation-group','lab:instrument-group','lab:inventory-group','lab:approval-group','lab:materials','lab:stock-batches','lab:stock-flows','lab:requisitions','lab:requisition-approvals','lab:inventory-warnings') OR menu.PERMISSION_CODE IN ('lab:material:manage','lab:stock:in','lab:stock:adjust','lab:requisition:create','lab:requisition:cancel','lab:requisition:approve'))
) source
ON (target.ROLE_ID=source.ROLE_ID AND target.MENU_ID=source.MENU_ID)
WHEN NOT MATCHED THEN INSERT (ID,ROLE_ID,MENU_ID,CREATE_TIME) VALUES (SYS_GUID(),source.ROLE_ID,source.MENU_ID,SYSTIMESTAMP);

-- 普通实验员可查询库存、提交和取消本人领用申请，但不能审批、入库或调整库存。
MERGE INTO HXS_SYS_ROLE_MENU target
USING (
    SELECT role.ID ROLE_ID, menu.ID MENU_ID
    FROM HXS_SYS_ROLE role CROSS JOIN HXS_SYS_MENU menu
    WHERE role.ROLE_CODE='lab_user'
      AND (menu.MENU_CODE IN ('lab','lab:foundation-group','lab:instrument-group','lab:inventory-group','lab:materials','lab:stock-batches','lab:stock-flows','lab:requisitions','lab:inventory-warnings') OR menu.PERMISSION_CODE IN ('lab:requisition:create','lab:requisition:cancel'))
) source
ON (target.ROLE_ID=source.ROLE_ID AND target.MENU_ID=source.MENU_ID)
WHEN NOT MATCHED THEN INSERT (ID,ROLE_ID,MENU_ID,CREATE_TIME) VALUES (SYS_GUID(),source.ROLE_ID,source.MENU_ID,SYSTIMESTAMP);

COMMIT;
