-- 阶段6：实验室二维/三维空间可视化。
-- 使用 HXS_AISYSTEM 用户执行，可重复执行；菜单和角色权限由应用初始化器幂等维护。
DECLARE
    object_count NUMBER;

    PROCEDURE ensure_table(name VARCHAR2, ddl CLOB) IS
    BEGIN
        SELECT COUNT(*) INTO object_count FROM USER_TABLES WHERE TABLE_NAME = name;
        IF object_count = 0 THEN EXECUTE IMMEDIATE ddl; END IF;
    END;

    PROCEDURE ensure_column(p_table_name VARCHAR2, p_column_name VARCHAR2, definition VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO object_count FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = p_table_name AND COLUMN_NAME = p_column_name;
        IF object_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' ADD ' || p_column_name || ' ' || definition;
        END IF;
    END;

    PROCEDURE ensure_fk(name VARCHAR2, table_name VARCHAR2, column_name VARCHAR2,
                        parent_table VARCHAR2, parent_column VARCHAR2) IS
        parent_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO object_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = name;
        SELECT COUNT(*) INTO parent_count FROM USER_TABLES WHERE TABLE_NAME = parent_table;
        IF object_count = 0 AND parent_count = 1 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || table_name || ' ADD CONSTRAINT ' || name ||
                ' FOREIGN KEY (' || column_name || ') REFERENCES ' || parent_table ||
                '(' || parent_column || ') ENABLE NOVALIDATE';
        END IF;
    END;

    PROCEDURE ensure_index(name VARCHAR2, ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO object_count FROM USER_INDEXES WHERE INDEX_NAME = name;
        IF object_count = 0 THEN EXECUTE IMMEDIATE ddl; END IF;
    END;
BEGIN
    ensure_table('HXS_LAB_3D_SCENE', q'[CREATE TABLE HXS_LAB_3D_SCENE (
        ID RAW(16) NOT NULL, LAB_ID RAW(16) NOT NULL, SCENE_NAME VARCHAR2(100 CHAR) NOT NULL,
        MODEL_URL VARCHAR2(500 CHAR), MODEL_FILE_ID RAW(16), VERSION NUMBER(10) DEFAULT 1 NOT NULL,
        BACKGROUND_COLOR VARCHAR2(20 CHAR) DEFAULT '#eef3f5' NOT NULL, IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_LAB_3D_SCENE PRIMARY KEY(ID))]');
    ensure_table('HXS_LAB_3D_NODE', q'[CREATE TABLE HXS_LAB_3D_NODE (
        ID RAW(16) NOT NULL, SCENE_ID RAW(16) NOT NULL, NODE_CODE VARCHAR2(80 CHAR) NOT NULL,
        NODE_NAME VARCHAR2(100 CHAR) NOT NULL, NODE_TYPE VARCHAR2(30 CHAR) NOT NULL,
        POSITION_X NUMBER(18,4) DEFAULT 0 NOT NULL, POSITION_Y NUMBER(18,4) DEFAULT 0 NOT NULL,
        POSITION_Z NUMBER(18,4) DEFAULT 0 NOT NULL, SCALE_X NUMBER(18,4) DEFAULT 1 NOT NULL,
        SCALE_Y NUMBER(18,4) DEFAULT 1 NOT NULL, SCALE_Z NUMBER(18,4) DEFAULT 1 NOT NULL,
        SORT_NO NUMBER(10) DEFAULT 0 NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_LAB_3D_NODE PRIMARY KEY(ID))]');
    ensure_table('HXS_LAB_3D_BINDING', q'[CREATE TABLE HXS_LAB_3D_BINDING (
        ID RAW(16) NOT NULL, NODE_ID RAW(16) NOT NULL, BUSINESS_TYPE VARCHAR2(30 CHAR) NOT NULL,
        BUSINESS_ID RAW(16) NOT NULL, CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_HXS_LAB_3D_BINDING PRIMARY KEY(ID))]');

    ensure_column('HXS_LAB_3D_SCENE', 'MODEL_FILE_ID', 'RAW(16)');
    ensure_column('HXS_LAB_3D_SCENE', 'VERSION', 'NUMBER(10) DEFAULT 1 NOT NULL');
    ensure_fk('FK_3D_SCENE_LAB', 'HXS_LAB_3D_SCENE', 'LAB_ID', 'HXS_LAB', 'ID');
    ensure_fk('FK_3D_SCENE_FILE', 'HXS_LAB_3D_SCENE', 'MODEL_FILE_ID', 'HXS_SYS_FILE', 'ID');
    ensure_fk('FK_3D_NODE_SCENE', 'HXS_LAB_3D_NODE', 'SCENE_ID', 'HXS_LAB_3D_SCENE', 'ID');
    ensure_fk('FK_3D_BIND_NODE', 'HXS_LAB_3D_BINDING', 'NODE_ID', 'HXS_LAB_3D_NODE', 'ID');
    ensure_index('UK_HXS_3D_SCENE_LAB_NAME', 'CREATE UNIQUE INDEX UK_HXS_3D_SCENE_LAB_NAME ON HXS_LAB_3D_SCENE(LAB_ID, SCENE_NAME)');
    ensure_index('UK_HXS_3D_NODE_CODE', 'CREATE UNIQUE INDEX UK_HXS_3D_NODE_CODE ON HXS_LAB_3D_NODE(SCENE_ID, NODE_CODE)');
    ensure_index('UK_HXS_3D_BINDING', 'CREATE UNIQUE INDEX UK_HXS_3D_BINDING ON HXS_LAB_3D_BINDING(NODE_ID, BUSINESS_TYPE, BUSINESS_ID)');
END;
/

COMMENT ON TABLE HXS_LAB_3D_SCENE IS '实验室三维场景及模型版本';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.LAB_ID IS '所属实验室ID';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.SCENE_NAME IS '场景名称';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.MODEL_URL IS '模型访问地址';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.MODEL_FILE_ID IS 'GLB模型文件记录ID';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.VERSION IS '场景模型版本号';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.BACKGROUND_COLOR IS '场景背景色';
COMMENT ON COLUMN HXS_LAB_3D_SCENE.IS_ACTIVE IS '是否启用：1是，0否';
COMMENT ON TABLE HXS_LAB_3D_NODE IS '三维场景空间与设备节点';
COMMENT ON COLUMN HXS_LAB_3D_NODE.SCENE_ID IS '所属三维场景ID';
COMMENT ON COLUMN HXS_LAB_3D_NODE.NODE_CODE IS '模型节点唯一编码';
COMMENT ON COLUMN HXS_LAB_3D_NODE.NODE_TYPE IS '节点类型：lab/location/instrument';
COMMENT ON TABLE HXS_LAB_3D_BINDING IS '三维节点与实验室业务数据绑定';
COMMENT ON COLUMN HXS_LAB_3D_BINDING.NODE_ID IS '三维节点ID';
COMMENT ON COLUMN HXS_LAB_3D_BINDING.BUSINESS_TYPE IS '业务类型：lab/location/instrument';
COMMENT ON COLUMN HXS_LAB_3D_BINDING.BUSINESS_ID IS '绑定业务数据ID';
COMMIT;

-- 验证：应返回 3 张表、模型文件列及 4 条外键。
SELECT TABLE_NAME, COMMENTS FROM USER_TAB_COMMENTS WHERE TABLE_NAME LIKE 'HXS_LAB_3D_%' ORDER BY TABLE_NAME;
SELECT TABLE_NAME, COLUMN_NAME, COMMENTS FROM USER_COL_COMMENTS WHERE TABLE_NAME LIKE 'HXS_LAB_3D_%' ORDER BY TABLE_NAME, COLUMN_NAME;
