using HxsAiSystem.Domain.Entities;
using SqlSugar;
namespace HxsAiSystem.Application.LabOperations;
public sealed class LabOperationsInitializer:ILabOperationsInitializer
{
    private readonly ISqlSugarClient _db;public LabOperationsInitializer(ISqlSugarClient db)=>_db=db;
    public async Task InitializeAsync(){var root=await _db.Queryable<SysMenu>().FirstAsync(x=>x.MenuCode=="lab")??throw new InvalidOperationException("实验室管理菜单不存在。");var parent=await _db.Queryable<SysMenu>().FirstAsync(x=>x.MenuCode=="lab:approval-group")??root;var now=DateTime.Now;var page=await Upsert("lab:approval-center","统一审批","page","/lab/approval-center","views/lab/ApprovalCenterView.vue","check","lab:approval:center:view",5,parent.Id,now);var button=await Upsert("permission:lab:approval:center:view","查看统一审批","button",null,null,"check","lab:approval:center:view",1000,page.Id,now);var export=await Upsert("permission:lab:export","导出实验室数据","button",null,null,"file","lab:export",1001,page.Id,now);foreach(var code in new[]{"admin","lab_admin","lab_user"}){var role=await _db.Queryable<SysRole>().FirstAsync(x=>x.RoleCode==code);if(role is null)continue;foreach(var menu in new[]{root,parent,page,button,export})if(!await _db.Queryable<SysRoleMenu>().AnyAsync(x=>x.RoleId==role.Id&&x.MenuId==menu.Id))await _db.Insertable(new SysRoleMenu{Id=Guid.NewGuid().ToByteArray(),RoleId=role.Id,MenuId=menu.Id,CreateTime=now}).ExecuteCommandAsync();}}
    private async Task<SysMenu> Upsert(string code,string name,string type,string? route,string? component,string icon,string? permission,int sort,byte[] parent,DateTime now){var x=await _db.Queryable<SysMenu>().FirstAsync(y=>y.MenuCode==code);if(x is null){x=new SysMenu{Id=Guid.NewGuid().ToByteArray(),ParentId=parent,MenuCode=code,MenuName=name,MenuType=type,RoutePath=route,Component=component,Icon=icon,PermissionCode=permission,SortNo=sort,IsVisible=type=="button"?0:1,IsActive=1,CreateTime=now,UpdateTime=now};await _db.Insertable(x).ExecuteCommandAsync();}else{x.ParentId=parent;x.MenuName=name;x.MenuType=type;x.RoutePath=route;x.Component=component;x.Icon=icon;x.PermissionCode=permission;x.SortNo=sort;x.IsVisible=type=="button"?0:1;x.IsActive=1;x.UpdateTime=now;await _db.Updateable(x).ExecuteCommandAsync();}return x;}
}
