using HxsAiSystem.Application.Auth;
using HxsAiSystem.Application.Common;
using HxsAiSystem.Domain.Entities;
using SqlSugar;

namespace HxsAiSystem.Application.LabInventory;

public sealed class LabInventoryService : ILabInventoryService
{
    private readonly ISqlSugarClient _db; private readonly ICurrentUserService _currentUser; private readonly IDataScopeService _dataScope;
    public LabInventoryService(ISqlSugarClient db, ICurrentUserService currentUser, IDataScopeService dataScope){_db=db;_currentUser=currentUser;_dataScope=dataScope;}

    public async Task<List<MaterialDto>> GetMaterialsAsync(bool enabledOnly=false){var q=_db.Queryable<LabMaterial>();if(enabledOnly)q=q.Where(x=>x.IsActive==1);return await MapMaterialsAsync(await q.OrderBy(x=>x.MaterialCode).ToListAsync());}
    public async Task<MaterialDto> CreateMaterialAsync(MaterialRequest r){ValidateMaterial(r,true);if(await _db.Queryable<LabMaterial>().AnyAsync(x=>x.MaterialCode==r.MaterialCode.Trim()))throw new InvalidOperationException("物资编码已存在。");await ValidateMaterialRefsAsync(r);var now=DateTime.Now;var x=new LabMaterial{Id=NewId(),MaterialCode=r.MaterialCode.Trim(),MaterialName=r.MaterialName.Trim(),MaterialType=r.MaterialType,CategoryId=RawGuidConverter.ToNullableRaw(r.CategoryId),Specification=Clean(r.Specification),CasNo=Clean(r.CasNo),UnitId=RawGuidConverter.ToRaw(r.UnitId),SupplierId=RawGuidConverter.ToNullableRaw(r.SupplierId),StorageLocationId=RawGuidConverter.ToRaw(r.StorageLocationId),MinStock=r.MinStock,Description=Clean(r.Description),IsActive=r.IsActive?1:0,CreateTime=now,UpdateTime=now};await _db.Insertable(x).ExecuteCommandAsync();return (await MapMaterialsAsync([x]))[0];}
    public async Task UpdateMaterialAsync(Guid id,MaterialRequest r){ValidateMaterial(r,false);await ValidateMaterialRefsAsync(r);var x=await FindAsync<LabMaterial>(id);x.MaterialName=r.MaterialName.Trim();x.MaterialType=r.MaterialType;x.CategoryId=RawGuidConverter.ToNullableRaw(r.CategoryId);x.Specification=Clean(r.Specification);x.CasNo=Clean(r.CasNo);x.UnitId=RawGuidConverter.ToRaw(r.UnitId);x.SupplierId=RawGuidConverter.ToNullableRaw(r.SupplierId);x.StorageLocationId=RawGuidConverter.ToRaw(r.StorageLocationId);x.MinStock=r.MinStock;x.Description=Clean(r.Description);x.IsActive=r.IsActive?1:0;x.UpdateTime=DateTime.Now;await _db.Updateable(x).ExecuteCommandAsync();}

    public async Task<List<StockBatchDto>> GetBatchesAsync(Guid? materialId=null){var q=_db.Queryable<LabStockBatch>();if(materialId.HasValue){var raw=RawGuidConverter.ToRaw(materialId.Value);q=q.Where(x=>x.MaterialId==raw);}return await MapBatchesAsync(await q.OrderByDescending(x=>x.StockInTime).ToListAsync());}
    public async Task<StockBatchDto> StockInAsync(StockInRequest r){Required(r.BatchNo,"批次号");if(r.Quantity<=0)throw new InvalidOperationException("入库数量必须大于0。");if(r.UnitPrice<0)throw new InvalidOperationException("单价不能小于0。");if(r.ProductionDate.HasValue&&r.ExpiryDate.HasValue&&r.ProductionDate.Value.Date>=r.ExpiryDate.Value.Date)throw new InvalidOperationException("有效期必须晚于生产日期。");var material=await FindAsync<LabMaterial>(r.MaterialId);if(material.IsActive!=1)throw new InvalidOperationException("物资已停用。");if(await _db.Queryable<LabStockBatch>().AnyAsync(x=>x.MaterialId==material.Id&&x.BatchNo==r.BatchNo.Trim()))throw new InvalidOperationException("该物资批次号已存在。");var now=DateTime.Now;await _db.Ado.BeginTranAsync();try{var batch=new LabStockBatch{Id=NewId(),MaterialId=material.Id,BatchNo=r.BatchNo.Trim(),ProductionDate=r.ProductionDate?.Date,ExpiryDate=r.ExpiryDate?.Date,InQuantity=r.Quantity,AvailableQuantity=r.Quantity,UnitPrice=r.UnitPrice,StockInTime=now,CreateTime=now,UpdateTime=now};await _db.Insertable(batch).ExecuteCommandAsync();await AddFlowAsync(batch,"in",r.Quantity,0,r.Quantity,"stock_in",batch.Id,r.Remark);await _db.Ado.CommitTranAsync();return (await MapBatchesAsync([batch]))[0];}catch{await _db.Ado.RollbackTranAsync();throw;}}
    public async Task AdjustStockAsync(Guid batchId,StockAdjustRequest r){if(r.Quantity==0)throw new InvalidOperationException("调整数量不能为0。");Required(r.Reason,"调整原因");await _db.Ado.BeginTranAsync();try{await LockAsync("HXS_LAB_STOCK_BATCH",batchId);var batch=await FindAsync<LabStockBatch>(batchId);var before=batch.AvailableQuantity;var after=before+r.Quantity;if(after<0)throw new InvalidOperationException("调整后库存不能小于0。");batch.AvailableQuantity=after;batch.UpdateTime=DateTime.Now;await _db.Updateable(batch).ExecuteCommandAsync();await AddFlowAsync(batch,"adjust",r.Quantity,before,after,"adjust",batch.Id,r.Reason);await _db.Ado.CommitTranAsync();}catch{await _db.Ado.RollbackTranAsync();throw;}}
    public async Task<List<StockFlowDto>> GetFlowsAsync(Guid? materialId=null){var q=_db.Queryable<LabStockFlow>();if(materialId.HasValue){var raw=RawGuidConverter.ToRaw(materialId.Value);q=q.Where(x=>x.MaterialId==raw);}return await MapFlowsAsync(await q.OrderByDescending(x=>x.CreateTime).ToListAsync());}

    public async Task<List<RequisitionDto>> GetRequisitionsAsync(bool mine=false,string? status=null){var q=_db.Queryable<LabRequisition>();if(mine||await _dataScope.GetCurrentScopeAsync()==DataScope.Self){var u=CurrentRaw();q=q.Where(x=>x.ApplicantId==u);}if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status);return await MapRequisitionsAsync(await q.OrderByDescending(x=>x.CreateTime).ToListAsync());}
    public async Task<RequisitionDto> CreateRequisitionAsync(RequisitionRequest r){Required(r.Purpose,"领用用途");if(r.Items.Count==0)throw new InvalidOperationException("至少添加一条领用明细。");var grouped=r.Items.GroupBy(x=>x.MaterialId).Select(x=>new RequisitionItemRequest{MaterialId=x.Key,Quantity=x.Sum(y=>y.Quantity)}).ToList();if(grouped.Any(x=>x.MaterialId==Guid.Empty||x.Quantity<=0))throw new InvalidOperationException("物资和领用数量无效。");foreach(var item in grouped){var material=await FindAsync<LabMaterial>(item.MaterialId);if(material.IsActive!=1)throw new InvalidOperationException($"物资 {material.MaterialName} 已停用。");}if(r.GroupId.HasValue)await FindAsync<LabGroup>(r.GroupId.Value);var now=DateTime.Now;await _db.Ado.BeginTranAsync();try{var req=new LabRequisition{Id=NewId(),RequisitionNo=No("RQ"),ApplicantId=CurrentRaw(),GroupId=RawGuidConverter.ToNullableRaw(r.GroupId),Purpose=r.Purpose.Trim(),Status="pending",CreateTime=now,UpdateTime=now};await _db.Insertable(req).ExecuteCommandAsync();var items=grouped.Select(x=>new LabRequisitionItem{Id=NewId(),RequisitionId=req.Id,MaterialId=RawGuidConverter.ToRaw(x.MaterialId),RequestQuantity=x.Quantity}).ToList();await _db.Insertable(items).ExecuteCommandAsync();await _db.Ado.CommitTranAsync();return (await MapRequisitionsAsync([req]))[0];}catch{await _db.Ado.RollbackTranAsync();throw;}}
    public async Task CancelRequisitionAsync(Guid id){var x=await FindAsync<LabRequisition>(id);if(!x.ApplicantId.SequenceEqual(CurrentRaw())&&await _dataScope.GetCurrentScopeAsync()==DataScope.Self)throw new UnauthorizedAccessException("只能取消本人申请。");if(x.Status!="pending")throw new InvalidOperationException("只有待审核申请可以取消。");x.Status="cancelled";x.UpdateTime=DateTime.Now;await _db.Updateable(x).ExecuteCommandAsync();}
    public async Task RejectRequisitionAsync(Guid id,RequisitionDecisionRequest r){await DecideWithoutStockAsync(id,"rejected",r.Remark);}
    private async Task DecideWithoutStockAsync(Guid id,string status,string? remark){await _db.Ado.BeginTranAsync();try{await LockAsync("HXS_LAB_REQUISITION",id);var x=await FindAsync<LabRequisition>(id);if(x.Status!="pending")throw new InvalidOperationException("领用申请已处理，不能重复审批。");x.Status=status;x.ApproverId=CurrentRaw();x.ApproveTime=DateTime.Now;x.ApproveRemark=Clean(remark);x.UpdateTime=DateTime.Now;await _db.Updateable(x).ExecuteCommandAsync();await _db.Ado.CommitTranAsync();}catch{await _db.Ado.RollbackTranAsync();throw;}}

    public async Task ApproveRequisitionAsync(Guid id,RequisitionApprovalRequest r)
    {
        await _db.Ado.BeginTranAsync();try
        {
            await LockAsync("HXS_LAB_REQUISITION",id);var req=await FindAsync<LabRequisition>(id);if(req.Status!="pending")throw new InvalidOperationException("领用申请已处理，不能重复审批。");
            var items=await _db.Queryable<LabRequisitionItem>().Where(x=>x.RequisitionId==req.Id).ToListAsync();var approvals=r.Items.ToDictionary(x=>x.ItemId,x=>x.ApprovedQuantity);
            var plans=new List<(LabRequisitionItem Item,decimal Quantity,List<LabStockBatch> Batches)>();
            foreach(var item in items)
            {
                var itemId=RawGuidConverter.ToGuid(item.Id);var qty=approvals.GetValueOrDefault(itemId,item.RequestQuantity);if(qty<=0||qty>item.RequestQuantity)throw new InvalidOperationException("批准数量必须大于0且不能超过申请数量。");
                var mid=RawGuidConverter.ToGuid(item.MaterialId);await _db.Ado.GetDataTableAsync($"SELECT ID FROM HXS_LAB_STOCK_BATCH WHERE MATERIAL_ID=HEXTORAW('{Convert.ToHexString(item.MaterialId)}') AND AVAILABLE_QUANTITY>0 AND (EXPIRY_DATE IS NULL OR EXPIRY_DATE>TRUNC(SYSDATE)) ORDER BY NVL(EXPIRY_DATE,DATE '9999-12-31'),STOCK_IN_TIME FOR UPDATE");
                var batches=await _db.Queryable<LabStockBatch>().Where(x=>x.MaterialId==item.MaterialId&&x.AvailableQuantity>0&&(x.ExpiryDate==null||x.ExpiryDate>DateTime.Today)).OrderBy(x=>x.ExpiryDate).OrderBy(x=>x.StockInTime).ToListAsync();if(batches.Sum(x=>x.AvailableQuantity)<qty){var material=await FindAsync<LabMaterial>(mid);throw new InvalidOperationException($"物资 {material.MaterialName} 库存不足。");}plans.Add((item,qty,batches));
            }
            foreach(var plan in plans)
            {
                var remaining=plan.Quantity;foreach(var batch in plan.Batches){if(remaining<=0)break;var take=Math.Min(batch.AvailableQuantity,remaining);var before=batch.AvailableQuantity;batch.AvailableQuantity-=take;batch.UpdateTime=DateTime.Now;await _db.Updateable(batch).ExecuteCommandAsync();await AddFlowAsync(batch,"out",-take,before,batch.AvailableQuantity,"requisition",req.Id,$"领用单 {req.RequisitionNo}");remaining-=take;}plan.Item.ApprovedQuantity=plan.Quantity;await _db.Updateable(plan.Item).UpdateColumns(x=>x.ApprovedQuantity).ExecuteCommandAsync();
            }
            req.Status="approved";req.ApproverId=CurrentRaw();req.ApproveTime=DateTime.Now;req.ApproveRemark=Clean(r.Remark);req.UpdateTime=DateTime.Now;await _db.Updateable(req).ExecuteCommandAsync();await _db.Ado.CommitTranAsync();
        }catch{await _db.Ado.RollbackTranAsync();throw;}
    }

    public async Task<List<InventoryWarningDto>> GetWarningsAsync(int expiryDays=30){expiryDays=Math.Clamp(expiryDays,1,365);var materials=await GetMaterialsAsync();var batches=await _db.Queryable<LabStockBatch>().Where(x=>x.AvailableQuantity>0).ToListAsync();var today=DateTime.Today;return materials.Select(x=>{var bs=batches.Where(b=>RawGuidConverter.ToGuid(b.MaterialId)==x.Id).ToList();var expired=bs.Count(b=>b.ExpiryDate.HasValue&&b.ExpiryDate.Value.Date<=today);var expiring=bs.Count(b=>b.ExpiryDate.HasValue&&b.ExpiryDate.Value.Date>today&&b.ExpiryDate.Value.Date<=today.AddDays(expiryDays));var status=expired>0?"expired":x.CurrentStock<=x.MinStock?"low":expiring>0?"expiring":"normal";return new InventoryWarningDto(x.Id,x.MaterialCode,x.MaterialName,x.CurrentStock,x.MinStock,expiring,expired,status);}).Where(x=>x.WarningStatus!="normal").OrderBy(x=>x.WarningStatus).ToList();}

    private async Task AddFlowAsync(LabStockBatch b,string type,decimal qty,decimal before,decimal after,string source,byte[]? sourceId,string? remark)=>await _db.Insertable(new LabStockFlow{Id=NewId(),FlowNo=No("FL"),MaterialId=b.MaterialId,BatchId=b.Id,FlowType=type,Quantity=qty,BeforeQuantity=before,AfterQuantity=after,SourceType=source,SourceId=sourceId,OperatorId=CurrentRaw(),Remark=Clean(remark),CreateTime=DateTime.Now}).ExecuteCommandAsync();
    private async Task ValidateMaterialRefsAsync(MaterialRequest r){if(r.UnitId==Guid.Empty||!await _db.Queryable<SysDictItem>().AnyAsync(x=>x.Id==RawGuidConverter.ToRaw(r.UnitId)&&x.IsActive==1))throw new InvalidOperationException("计量单位不存在或已停用。");if(r.StorageLocationId==Guid.Empty||!await _db.Queryable<LabLocation>().AnyAsync(x=>x.Id==RawGuidConverter.ToRaw(r.StorageLocationId)&&x.IsActive==1))throw new InvalidOperationException("存放位置不存在或已停用。");}
    private async Task LockAsync(string table,Guid id)=>await _db.Ado.GetDataTableAsync($"SELECT ID FROM {table} WHERE ID=HEXTORAW('{Convert.ToHexString(id.ToByteArray())}') FOR UPDATE");
    private async Task<T> FindAsync<T>(Guid id)where T:class,new()=>await _db.Queryable<T>().Where($"ID=HEXTORAW('{Convert.ToHexString(id.ToByteArray())}')").FirstAsync()??throw new KeyNotFoundException("记录不存在。");
    private byte[] CurrentRaw()=>RawGuidConverter.ToRaw(_currentUser.GetUserId()??throw new UnauthorizedAccessException("用户未登录。"));private static byte[] NewId()=>Guid.NewGuid().ToByteArray();private static string No(string p)=>$"{p}{DateTime.Now:yyyyMMddHHmmssfff}{Guid.NewGuid():N}"[..Math.Min(40,p.Length+23)];private static string? Clean(string?s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim();private static void Required(string?s,string n){if(string.IsNullOrWhiteSpace(s))throw new InvalidOperationException($"{n}不能为空。");}private static void ValidateMaterial(MaterialRequest r,bool create){if(create)Required(r.MaterialCode,"物资编码");Required(r.MaterialName,"物资名称");if(r.MaterialType is not("reagent" or "consumable"))throw new InvalidOperationException("物资类型无效。");if(r.MinStock<0)throw new InvalidOperationException("最低库存不能小于0。");}

    private async Task<List<MaterialDto>> MapMaterialsAsync(List<LabMaterial> rows){var items=(await _db.Queryable<SysDictItem>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var sups=(await _db.Queryable<LabSupplier>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var locs=(await _db.Queryable<LabLocation>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var batches=await _db.Queryable<LabStockBatch>().ToListAsync();var stocks=batches.GroupBy(x=>RawGuidConverter.ToGuid(x.MaterialId)).ToDictionary(x=>x.Key,x=>x.Sum(y=>y.AvailableQuantity));return rows.Select(x=>{Guid? c=x.CategoryId is null?null:RawGuidConverter.ToGuid(x.CategoryId);Guid? s=x.SupplierId is null?null:RawGuidConverter.ToGuid(x.SupplierId);var u=RawGuidConverter.ToGuid(x.UnitId);var l=RawGuidConverter.ToGuid(x.StorageLocationId);return new MaterialDto(RawGuidConverter.ToGuid(x.Id),x.MaterialCode,x.MaterialName,x.MaterialType,c,c.HasValue?items.GetValueOrDefault(c.Value)?.ItemLabel:null,x.Specification,x.CasNo,u,items.GetValueOrDefault(u)?.ItemLabel,s,s.HasValue?sups.GetValueOrDefault(s.Value)?.SupplierName:null,l,locs.GetValueOrDefault(l)?.LocationName,x.MinStock,stocks.GetValueOrDefault(RawGuidConverter.ToGuid(x.Id)),x.Description,x.IsActive==1);}).ToList();}
    private async Task<List<StockBatchDto>> MapBatchesAsync(List<LabStockBatch> rows){var ms=(await _db.Queryable<LabMaterial>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var today=DateTime.Today;return rows.Select(x=>new StockBatchDto(RawGuidConverter.ToGuid(x.Id),RawGuidConverter.ToGuid(x.MaterialId),ms.GetValueOrDefault(RawGuidConverter.ToGuid(x.MaterialId))?.MaterialName,x.BatchNo,x.ProductionDate,x.ExpiryDate,x.InQuantity,x.AvailableQuantity,x.UnitPrice,x.StockInTime,x.ExpiryDate.HasValue&&x.ExpiryDate.Value.Date<=today?"expired":x.ExpiryDate.HasValue&&x.ExpiryDate.Value.Date<=today.AddDays(30)?"expiring":"normal")).ToList();}
    private async Task<List<StockFlowDto>> MapFlowsAsync(List<LabStockFlow> rows){var ms=(await _db.Queryable<LabMaterial>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var bs=(await _db.Queryable<LabStockBatch>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var us=(await _db.Queryable<AppUser>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));return rows.Select(x=>{var m=RawGuidConverter.ToGuid(x.MaterialId);var b=RawGuidConverter.ToGuid(x.BatchId);var u=RawGuidConverter.ToGuid(x.OperatorId);return new StockFlowDto(RawGuidConverter.ToGuid(x.Id),x.FlowNo,m,ms.GetValueOrDefault(m)?.MaterialName,b,bs.GetValueOrDefault(b)?.BatchNo,x.FlowType,x.Quantity,x.BeforeQuantity,x.AfterQuantity,x.SourceType,x.SourceId is null?null:RawGuidConverter.ToGuid(x.SourceId),u,us.GetValueOrDefault(u)?.DisplayName??us.GetValueOrDefault(u)?.UserName,x.Remark,x.CreateTime);}).ToList();}
    private async Task<List<RequisitionDto>> MapRequisitionsAsync(List<LabRequisition> rows){var users=(await _db.Queryable<AppUser>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var groups=(await _db.Queryable<LabGroup>().ToListAsync()).ToDictionary(x=>RawGuidConverter.ToGuid(x.Id));var materials=(await GetMaterialsAsync()).ToDictionary(x=>x.Id);var all=await _db.Queryable<LabRequisitionItem>().ToListAsync();return rows.Select(x=>{var id=RawGuidConverter.ToGuid(x.Id);var a=RawGuidConverter.ToGuid(x.ApplicantId);Guid? g=x.GroupId is null?null:RawGuidConverter.ToGuid(x.GroupId);Guid? ap=x.ApproverId is null?null:RawGuidConverter.ToGuid(x.ApproverId);var items=all.Where(i=>i.RequisitionId.SequenceEqual(x.Id)).Select(i=>{var m=RawGuidConverter.ToGuid(i.MaterialId);return new RequisitionItemDto(RawGuidConverter.ToGuid(i.Id),m,materials.GetValueOrDefault(m)?.MaterialName,materials.GetValueOrDefault(m)?.UnitName,i.RequestQuantity,i.ApprovedQuantity);}).ToList();return new RequisitionDto(id,x.RequisitionNo,a,users.GetValueOrDefault(a)?.DisplayName??users.GetValueOrDefault(a)?.UserName,g,g.HasValue?groups.GetValueOrDefault(g.Value)?.GroupName:null,x.Purpose,x.Status,ap,ap.HasValue?users.GetValueOrDefault(ap.Value)?.DisplayName??users.GetValueOrDefault(ap.Value)?.UserName:null,x.ApproveTime,x.ApproveRemark,x.CreateTime,items);}).ToList();}
}
